SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{697B6CBAF5199832}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{697B6CBAF519983A}" {
     m_aEntityDataList {
      SCR_EntityCatalogLoadoutData "{697B6CBAF519983B}" {
       m_eRequiredRank RENEGADE
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{697B6CBAF5199838}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{697B6CBAF5199839}" {
     m_aEntityDataList {
      SCR_EntityCatalogLoadoutData "{697B6CBAF5199806}" {
       m_eRequiredRank RENEGADE
      }
     }
    }
    SCR_EntityCatalogEntry "{697B6CBAF51964EC}" {
     m_aEntityDataList {
      SCR_EntityCatalogLoadoutData "{697B6CBAF51964ED}" {
       m_eRequiredRank RENEGADE
      }
     }
    }
   }
  }
 }
}