SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60569780DE4EE17A}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{64ED11C00A5190F8}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64ED11C06F67E657}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64ED11C06D13EE4E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68CB0C694694CA68}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64ED11C06CD0E8C0}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6906B0331E915A0F}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6906B0330239743F}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6906B0330991905F}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6979212C8879905E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64ED11C013E1122E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64ED11C049C3D3DA}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64ED11C048F8F140}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68CB0C68BD7ADD40}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64ED11C04F93E929}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64ED11C04F2878D9}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64ED11C04E7D6EB3}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68CB0C68AD1AD2C6}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64ED11C04D324548}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64ED11C0B3A3B0CE}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64ED11C0B23E59BB}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68CB0C68E85FDC8D}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{69076899ABA62365}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{69076899889B857C}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{690768998EF601E1}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{690768993B017C31}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{69076899771D3A1E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6907689954972F3E}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{69076899582E27FD}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{690768994C4A65A0}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65CE9EF6F71BB28D}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65CE9EF650E3CF06}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{65CE9EF64C868ABC}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{68CB0C68E7760FA4}" {
     m_bEnabled 0
    }
   }
  }
 }
}