SCR_EntityCatalog {
 m_eEntityCatalogType WEAPONS_TRIPOD
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{68E4962131815391}" {
   m_sEntityPrefab "{73530808E4B455BA}Prefabs/Weapons/Tripods/Tripod_M3_M2HB.et"
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{68E4962131815396}" {
   m_sEntityPrefab "{887DB60486A18575}Prefabs/Weapons/Tripods/Tripod_M122_MG_M60.et"
   m_bEnabled 0
  }
 }
}