SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Pistols (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB7D72187CE}" {
   m_sEntityPrefab "{C0F7DD85A86B2900}Prefabs/Weapons/Handguns/PM/Handgun_PM.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D72187D4}" {
     m_eItemType PISTOL
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}