SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Machine Guns (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB7D21C85AB}" {
   m_sEntityPrefab "{591519C23638AFD0}Prefabs/Weapons/MachineGuns/RPK74N/MG_RPK74N.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D21C85AC}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D21C85A3}" {
   m_sEntityPrefab "{04EF72C0FE07A93F}Prefabs/Weapons/MachineGuns/RPK74N/MG_RPK74N_1P78.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D21C09D7}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D21C09D5}" {
   m_sEntityPrefab "{8D789CE7C2C01A9C}Prefabs/Weapons/MachineGuns/RPK74N/MG_RPK74N_1pn93.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D21C09D2}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D21C6264}" {
   m_sEntityPrefab "{4C995EA1C0E79A28}Prefabs/Weapons/MachineGuns/RPK74N/MG_RPK74N_Railed.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D21C6265}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D21C6266}" {
   m_sEntityPrefab "{4D037FD67904B589}Prefabs/Weapons/MachineGuns/RPK74N/MG_RPK74N_Railed_1P87.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D21C6267}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D21C60E3}" {
   m_sEntityPrefab "{4EF6890D756306D1}Prefabs/Weapons/MachineGuns/RPK74M/MG_RPK74M.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D21C60DD}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D21C60DE}" {
   m_sEntityPrefab "{8673F10B6993BE33}Prefabs/Weapons/MachineGuns/RPK74M/MG_RPK74M_1P78.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D21C60D4}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D21C60D5}" {
   m_sEntityPrefab "{FB4C5D429348F1A2}Prefabs/Weapons/MachineGuns/RPK74M/MG_RPK74M_NPZ.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D21DB9A7}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D21DB9A4}" {
   m_sEntityPrefab "{5D6226C0B4631749}Prefabs/Weapons/MachineGuns/PKM/MG_PKM_B51.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D21DB9A5}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D21DB9A2}" {
   m_sEntityPrefab "{BC090DB2DEE8D5FB}Prefabs/Weapons/MachineGuns/PKM/MG_PKM_B51_1p86.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D21DE4F9}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D21DE4F8}" {
   m_sEntityPrefab "{5995414BD20D4290}Prefabs/Weapons/MachineGuns/PKM/MG_PKM_B51_1p87.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D21DE4FB}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D21DC178}" {
   m_sEntityPrefab "{4BE4931DF7B1ABCD}Prefabs/Weapons/MachineGuns/PKM/MG_PKM_B51_Eot.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D21DC179}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
 }
}