SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Carbine Rifles (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB7AD0483BA}" {
   m_sEntityPrefab "{1D7DEE0F174D636F}Prefabs/Weapons/Rifles/PP19/Rifle_PP19.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7AD0483B4}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7AD0483B2}" {
   m_sEntityPrefab "{E00D722F11D21FB3}Prefabs/Weapons/Rifles/PP19/Rifle_PP19_zenit.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7AD0483B0}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7AD0483B1}" {
   m_sEntityPrefab "{40030490DBE4CCA6}Prefabs/Weapons/Rifles/VPO185/Rifle_VPO185_MOD1.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7AD04838E}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7AD040BA1}" {
   m_sEntityPrefab "{91050AFE91FBBEB5}Prefabs/Weapons/Rifles/VPO185/Rifle_VPO185_Suppressed.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7AD040BA3}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7AD05E475}" {
   m_sEntityPrefab "{FED794DFBA068835}Prefabs/Weapons/Rifles/ASVAL/Rifle_ASVAL.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7AD05E474}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7AD05E473}" {
   m_sEntityPrefab "{79239AD11D3A64DD}Prefabs/Weapons/Rifles/ASVAL/Rifle_ASVAL_MOD.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7AD05E472}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7AD05984B}" {
   m_sEntityPrefab "{57E5E14855E32F81}Prefabs/Weapons/Rifles/ASVAL/Rifle_ASVAL_MOD_B13.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7AD059848}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}