SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Snipers (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB7DE777DEB}" {
   m_sEntityPrefab "{3EB02CDAD5F23C82}Prefabs/Weapons/Rifles/SVD/Rifle_SVD.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7DE777DEE}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7DE777DD3}" {
   m_sEntityPrefab "{6415B7923DE28C1B}Prefabs/Weapons/Rifles/SVD/Rifle_SVD_PSO.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7DE777DD2}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}