SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Snipers (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB7C0C1F510}" {
   m_sEntityPrefab "{C828F6D563E1A9BE}Prefabs/Weapons/Rifles/SVD/Rifle_SVD_PSO_7N14.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7C0C1F516}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7C0C1F518}" {
   m_sEntityPrefab "{20E0F308CE8953F8}Prefabs/Weapons/Rifles/SVD/Rifle_SVD_1P21_7N14.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7C0C1F51B}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7C0C1F51A}" {
   m_sEntityPrefab "{455E257F80BE6C1B}Prefabs/Weapons/Rifles/SVD/Rifle_SVD_1pn93.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7C0C1F51D}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
 }
}