SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Pistols (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB7D98D7059}" {
   m_sEntityPrefab "{880A80C1FD1AE546}Prefabs/Weapons/Handguns/APS/Handgun_APS.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D98D705F}" {
     m_eItemType PISTOL
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D98D7020}" {
   m_sEntityPrefab "{A8B4089ACB473848}Prefabs/Weapons/Handguns/MP443/Handgun_MP443.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D98D68B4}" {
     m_eItemType PISTOL
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D98D68B1}" {
   m_sEntityPrefab "{E998FA484B0C4BFF}Prefabs/Weapons/Handguns/Glock/Handgun_Glock17.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D98CBF9B}" {
     m_eItemType PISTOL
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D98CBF9A}" {
   m_sEntityPrefab "{8983A91174EE3799}Prefabs/Weapons/Handguns/Glock/Handgun_Glock45.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D98CBF99}" {
     m_eItemType PISTOL
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D98C08B0}" {
   m_sEntityPrefab "{A5088C056E06D479}Prefabs/Weapons/Handguns/SP81/Handgun_SP81.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D98C08B1}" {
     m_eItemType PISTOL
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}