SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Launchers (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB7AC69BEBC}" {
   m_sEntityPrefab "{722CE6FEC39EE896}Prefabs/Weapons/Launchers/RPG22/Launcher_RPG22.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7AC69BEB6}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 50
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7AC69BEB5}" {
   m_sEntityPrefab "{7A82FE978603F137}Prefabs/Weapons/Launchers/RPG7/Launcher_RPG7.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7AC6973C8}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}