SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Machine Guns (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB7D3D969E2}" {
   m_sEntityPrefab "{A7AF84C6C58BA3E8}Prefabs/Weapons/MachineGuns/RPK74/MG_RPK74.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D3D969E4}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D3D969DA}" {
   m_sEntityPrefab "{5F365605E36597FB}Prefabs/Weapons/MachineGuns/RPK74/MG_RPK74N.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D3D969DB}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D3D969D8}" {
   m_sEntityPrefab "{A89BC9D55FFB4CD8}Prefabs/Weapons/MachineGuns/PKM/MG_PKM.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D3D969D9}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D3D969DE}" {
   m_sEntityPrefab "{80CBC9A8D95A8A7B}Prefabs/Weapons/MachineGuns/PKM/MG_PKMN.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D3D969DF}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
 }
}