SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Pistols (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB7D8DD686B}" {
   m_sEntityPrefab "{9881625B28C94079}Prefabs/Weapons/Handguns/G19/Handgun_G19_RU.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D8DD6855}" {
     m_eItemType PISTOL
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB7D8DD6850}" {
   m_sEntityPrefab "{6491372D0534BA93}Prefabs/Weapons/Handguns/G19/Handgun_G19_MOD1_RU.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB7D8DD6851}" {
     m_eItemType PISTOL
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}