SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Machine Guns (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D71093C43EC38}" {
   m_sEntityPrefab "{4FCBBDF274FD2157}Prefabs/Weapons/Magazines/Box_556x45_M249_200rnd_Ball.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093C43EC22}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093C43EC20}" {
   m_sEntityPrefab "{06D722FC2666EB83}Prefabs/Weapons/Magazines/Box_556x45_M249_200rnd_4Ball_1Tracer.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093C43EC21}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093C43EC26}" {
   m_sEntityPrefab "{4EEDDB27C023B8B9}Prefabs/Weapons/Magazines/Box_556x45_M249_200rnd_Tracer.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093C43EC27}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093C43EC24}" {
   m_sEntityPrefab "{982F5BA41A3738CF}Prefabs/Weapons/Magazines/Box_762x51_M60_100rnd_Ball.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093C43EC25}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093C43E915}" {
   m_sEntityPrefab "{4D2C1E8F3A81F894}Prefabs/Weapons/Magazines/Box_762x51_M60_100rnd_4Ball_1Tracer.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093C43E91B}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093C43E918}" {
   m_sEntityPrefab "{AD8AB93729348C3E}Prefabs/Weapons/Magazines/Box_762x51_M60_100rnd_Tracer.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093C43E919}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093C43E91E}" {
   m_sEntityPrefab "{75632A0CA07D3817}Prefabs/Weapons/Magazines/Box_762x51_M60_100rnd_AP.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093C43E961}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093C43DAC1}" {
   m_sEntityPrefab "{AAF51CFA75A9CF8B}Prefabs/Weapons/Magazines/Box_762x51_M60_100rnd_4AP_1Tracer.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093C43DAC6}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
 }
}