SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Machine Guns (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710920B0842B}" {
   m_sEntityPrefab "{68022E6731BD0DCA}Prefabs/Weapons/Magazines/556x45_M249_200rnd/Box_556x45_M249_200rnd_4Ball_1Tracer_M855_M856.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710920B08420}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710920B08423}" {
   m_sEntityPrefab "{473FA589F017AE09}Prefabs/Weapons/Magazines/556x45_M249_200rnd/Box_556x45_M249_200rnd_4AP_1Tracer_M855A1_M856.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710920B0843C}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710920B0843D}" {
   m_sEntityPrefab "{7BB85ED0ABCF50E0}Prefabs/Weapons/Magazines/556x45_M249_200rnd/Box_556x45_M249_200rnd_Tracer_M856.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710920B0843F}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710920B02CAA}" {
   m_sEntityPrefab "{9B7E2FB6AF1150F0}Prefabs/Weapons/Magazines/762x51_M60_100rnd/Box_762x51_M60_100rnd_4Ball_1Tracer_M80_M62.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710920B02CAD}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710920B02CAC}" {
   m_sEntityPrefab "{7800FE7DDFC898F1}Prefabs/Weapons/Magazines/762x51_M60_100rnd/Box_762x51_M60_100rnd_4AP_M61_M62.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710920B02CAF}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710920B0161F}" {
   m_sEntityPrefab "{6D4E16A1B382AAE1}Prefabs/Weapons/Magazines/762x51_M60_100rnd/Box_762x51_M60_100rnd_Tracer_M62.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710920B0161E}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
 }
}