SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Vehicles (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D71095E429E47}" {
   m_sEntityPrefab "{BD814A1DB2905053}Prefabs/Weapons/Magazines/Box_23x152_ZU23_100rnd_2HEIT_1APIT_Red.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71095E429E4C}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 20
    }
   }
  }
 }
}