SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Grenade Launchers (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D71090B34B95B}" {
   m_sEntityPrefab "{9B440C384587DCFA}Prefabs/Weapons/Ammo/Ammo_Grenade_Stun_M406.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71090B34B955}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
 }
}