SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Launchers (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710939D48B46}" {
   m_sEntityPrefab "{319873694735DE0F}Prefabs/Weapons/Magazines/MK153/Container_MK153_NE.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710939D48B4C}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710939D48B4E}" {
   m_sEntityPrefab "{27AC9FC7F5E2BEEB}Prefabs/Weapons/Magazines/MK153/Container_MK153_HEDP.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710939D48B4F}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710939D48B48}" {
   m_sEntityPrefab "{2C935EF6F98E6354}Prefabs/Weapons/Magazines/MK153/Container_MK153_HEAA.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710939D48B49}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
 }
}