SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Grenade Launchers (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710907AA4E02}" {
   m_sEntityPrefab "{1663496AE5B9F10B}Prefabs/Weapons/Ammo/Ammo_Grenade_HEDP_M433.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710907AA4E07}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710907AA4E0A}" {
   m_sEntityPrefab "{5375FA7CB1F68573}Prefabs/Weapons/Ammo/Ammo_Grenade_HE_M406.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710907AA4E0B}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710907AA4E0C}" {
   m_sEntityPrefab "{98DB57ECEDC81CC2}Prefabs/Weapons/Ammo/Ammo_Flare_40mm_M583A1_White.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710907AA7777}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710907AA7775}" {
   m_sEntityPrefab "{0AF10C206CF1A283}Prefabs/Weapons/Ammo/Ammo_Flare_40mm_M661_Green.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710907ABB659}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710907ABB658}" {
   m_sEntityPrefab "{2A63C909016C4C41}Prefabs/Weapons/Ammo/Ammo_Flare_40mm_M662_Red.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710907ABB667}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
 }
}