SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Machine Guns (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D71093E927213}" {
   m_sEntityPrefab "{E8E9972833CB4203}Prefabs/Weapons/Magazines/Box_556x45_M249_200rnd_M855A1_Ball.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093E927215}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093E927218}" {
   m_sEntityPrefab "{BEE3897D2286992A}Prefabs/Weapons/Magazines/Box_556x45_M249_200rnd_M855A1_4Ball_1Tracer.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093E927219}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093E92721E}" {
   m_sEntityPrefab "{982F5BA41A3738CF}Prefabs/Weapons/Magazines/Box_762x51_M60_100rnd_Ball.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093E92721F}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093E9220B1}" {
   m_sEntityPrefab "{4D2C1E8F3A81F894}Prefabs/Weapons/Magazines/Box_762x51_M60_100rnd_4Ball_1Tracer.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093E9220B3}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093E92208C}" {
   m_sEntityPrefab "{AD8AB93729348C3E}Prefabs/Weapons/Magazines/Box_762x51_M60_100rnd_Tracer.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093E92208D}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
 }
}