SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Pistols (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710924EF9B82}" {
   m_sEntityPrefab "{F20D1122BC5CD9F2}Prefabs/Weapons/Magazines/glock_magazine/Magazine_9x19_Glock_17rnd.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710924EF9B9B}" {
     m_eItemType PISTOL
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710924EF9B9C}" {
   m_sEntityPrefab "{0CAD83389EE8E3DC}Prefabs/Weapons/Magazines/glock_magazine/Magazine_9x19_Glock_17rnd_tan.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710924E8512F}" {
     m_eItemType PISTOL
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710924E8512D}" {
   m_sEntityPrefab "{8FF49793853DB2F9}Prefabs/Weapons/Magazines/m17_magazines/Magazine_9x19_m17_17rnd_M1152.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710924E85122}" {
     m_eItemType PISTOL
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710924E85123}" {
   m_sEntityPrefab "{378685356C8F72E6}Prefabs/Weapons/Magazines/m17_magazines/Magazine_9x19_m17_24rnd_M1152.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710924E819E7}" {
     m_eItemType PISTOL
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
 }
}