SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Pistols (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710922B8BABA}" {
   m_sEntityPrefab "{9C05543A503DB80E}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_Ball.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710922B8BAB0}" {
     m_eItemType PISTOL
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
 }
}