SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Launchers (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D71093A7B9898}" {
   m_sEntityPrefab "{69D43140603EB1BC}Prefabs/Weapons/Ammo/Ammo_Rocket_HEAT751.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093A7B9886}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 40
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093A7B9881}" {
   m_sEntityPrefab "{0B1906A687028974}Prefabs/Weapons/Ammo/Ammo_Rocket_HEDP502.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093A7B9882}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 40
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093A7B9883}" {
   m_sEntityPrefab "{972E4239C2F8D0DB}Prefabs/Weapons/Ammo/Ammo_Rocket_HE411B.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093A7B988C}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 40
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093A7B988D}" {
   m_sEntityPrefab "{A1C421AFF9E5CFC7}Prefabs/Weapons/Ammo/Ammo_Rocket_SMOKE469C.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093A7BDDE9}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 40
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093A7BDDEB}" {
   m_sEntityPrefab "{77B57B7FB70AFA3B}Prefabs/Weapons/Ammo/Ammo_Rocket_ILLUM545C.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093A7BDDEC}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 20
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093A7B355A}" {
   m_sEntityPrefab "{319873694735DE0F}Prefabs/Weapons/Magazines/MK153/Container_MK153_NE.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093A7B355B}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 40
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093A7B3558}" {
   m_sEntityPrefab "{27AC9FC7F5E2BEEB}Prefabs/Weapons/Magazines/MK153/Container_MK153_HEDP.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093A7B3559}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 40
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71093A7B3526}" {
   m_sEntityPrefab "{2C935EF6F98E6354}Prefabs/Weapons/Magazines/MK153/Container_MK153_HEAA.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71093A7A94D2}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 40
    }
   }
  }
 }
}