SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Footwear (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB566BBEEF5}" {
   m_sEntityPrefab "{C7923961D7235D70}Prefabs/Characters/Footwear/CombatBoots_Soviet_01.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB566BBEEF2}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB566BBEEEF}" {
   m_sEntityPrefab "{4C6029AB8BF5C044}Prefabs/Characters/Footwear/CombatBoots_Soviet_01_Dirty.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB566BB6AC4}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}