SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Suits (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB6306B44DE}" {
   m_sEntityPrefab "{17A9B50472CCD255}Prefabs/Characters/Uniforms/Suit_Coverall/Suit_Coverall_ATACSFG.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6306B44DB}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6306B44C7}" {
   m_sEntityPrefab "{5062C2A8F9D93B48}Prefabs/Characters/Uniforms/Suit_Coverall/Suit_Coverall_EMR.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6306A8829}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6306A882F}" {
   m_sEntityPrefab "{AF754CFC07D3F4BA}Prefabs/Characters/Uniforms/Suit_Coverall/Suit_Coverall_KLMK.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6306A882C}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6306A882D}" {
   m_sEntityPrefab "{EC4904798055A75D}Prefabs/Characters/Uniforms/Suit_Coverall/Suit_Coverall_Partizan_Autumn.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6306A8822}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6306AB4DF}" {
   m_sEntityPrefab "{83EF5A8226533196}Prefabs/Characters/Uniforms/Suit_Coverall/Suit_Coverall_Partizan_Spring.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6306AB4DE}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6306AB4DD}" {
   m_sEntityPrefab "{D32AD628832D3FD2}Prefabs/Characters/Uniforms/Suit_Coverall/Suit_Coverall_Partizan_Summer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6306A0A03}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6306A0A02}" {
   m_sEntityPrefab "{1947AD605AAF5737}Prefabs/Characters/Uniforms/Suit_Coverall/Suit_Coverall_Spectre.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6306A0A05}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6306A3FC2}" {
   m_sEntityPrefab "{5E628798035BAE7C}Prefabs/Characters/Uniforms/Suit_Coverall/Suit_Coverall_Spectre_SKWO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6306A3FC3}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
 }
}