SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Backpacks (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB57BC90F26}" {
   m_sEntityPrefab "{CAEDE923EF4071AE}Prefabs/Items/Equipment/Backpacks/Backpack_Suharka_type1.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB57BC90F3C}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB57BC90F31}" {
   m_sEntityPrefab "{A6B9DDC35384FE80}Prefabs/Items/Equipment/Backpacks/Backpack_Suharka_type2.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB57BC90F30}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB57BC90F33}" {
   m_sEntityPrefab "{45DC01791EBE2349}Prefabs/Items/Equipment/Backpacks/backpack_Wartech_BB102/Backpack_Wartech_BB102_EMR.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB57BC694C4}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB57BC694C2}" {
   m_sEntityPrefab "{78529FDEF5EA8C29}Prefabs/Items/Equipment/Backpacks/Backpack_Wartech_BB102/Backpack_Wartech_BB102_EMR_Desert.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB57BC694C3}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB57BC6AA3D}" {
   m_sEntityPrefab "{16C7AD0508F53A9B}Prefabs/Items/Equipment/Backpacks/backpack_Wartech_BB102/Backpack_Wartech_BB102_OD.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB57BC6AA3E}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB57BC6AA3F}" {
   m_sEntityPrefab "{72DB97161FBA7AF0}Prefabs/Items/Equipment/Backpacks/backpack_Wartech_BB102/Backpack_Wartech_BB102_FG.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB57BC6ABC0}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB57BC6ABC1}" {
   m_sEntityPrefab "{C5E7592C94DC6D4C}Prefabs/Items/Equipment/Backpacks/backpack_Wartech_BB102/Backpack_Wartech_BB102_MC.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB57BC601D1}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB57BC601D2}" {
   m_sEntityPrefab "{99B347D92F16A6D3}Prefabs/Items/Equipment/Backpacks/backpack_511_rush12/Backpack_511_rush12_od.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB57BC601D3}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB57BC601D4}" {
   m_sEntityPrefab "{DF886C6B22F49827}Prefabs/Items/Equipment/Backpacks/backpack_511_rush12/Backpack_511_rush12_black.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB57BC7F582}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
 }
}