SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Suits (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB60C18792D}" {
   m_sEntityPrefab "{CF221A167DE87E57}Prefabs/Characters/Uniforms/Suit_KLMK/Suit_KLMK.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB60C187954}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
 }
}