SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Helmets (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB6DB351516}" {
   m_sEntityPrefab "{F59947DC816493A1}Prefabs/Characters/HeadGear/Helmets/Helmet_TSh4/Helmet_TSh4_Folded.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6DB3515ED}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6DB3515EE}" {
   m_sEntityPrefab "{6B5196ECD70773A0}Prefabs/Characters/HeadGear/Helmets/Helmet_TSh4/Helmet_TSh4_Unfolded.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6DB3515E9}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6DB3515E8}" {
   m_sEntityPrefab "{AB898107D202B1F0}Prefabs/Characters/HeadGear/Helmets/Helmet_Altyn/Helmet_Altyn.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6DB3571F1}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}