SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Backpacks (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB5787BF06C}" {
   m_sEntityPrefab "{54C68E438DD34265}Prefabs/Items/Equipment/Radios/Radio_R107M.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5787BF012}" {
     m_eItemType RADIO_BACKPACK
     m_iSupplyCost 50
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5787BF015}" {
   m_sEntityPrefab "{3DE0155EC9767B98}Prefabs/Items/Equipment/Backpacks/Backpack_Veshmeshok.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5787B6FBB}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5787B6FB9}" {
   m_sEntityPrefab "{443304F1EC50BC27}Prefabs/Items/Equipment/Backpacks/Backpack_Veshmeshok_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5787B6FB6}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5787B6FB7}" {
   m_sEntityPrefab "{41A9C55B61F375F0}Prefabs/Items/Equipment/Backpacks/Backpack_Kolobok.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5787B6FB4}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5787AAB4F}" {
   m_sEntityPrefab "{0D39750E5695B9D8}Prefabs/Items/Equipment/Backpacks/Backpack_RPG_Gunner.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5787AAB4E}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5787AAB49}" {
   m_sEntityPrefab "{9A201604DEF3BAAC}Prefabs/Items/Equipment/Backpacks/Backpack_RPG_Gunner_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5787AAB48}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5787A07FE}" {
   m_sEntityPrefab "{6A39B5843B3F36DA}Prefabs/Items/Equipment/Backpacks/Backpack_RPG_Assistant.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5787A07E6}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5787A07E5}" {
   m_sEntityPrefab "{26223738A07F8202}Prefabs/Items/Equipment/Backpacks/Backpack_RPG_Assistant_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5787A07E4}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5787A5A9E}" {
   m_sEntityPrefab "{7AC107CA7AFC9B59}Prefabs/Items/Equipment/Backpacks/Backpack_Medical_Soviet.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5787A5A91}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
 }
}