SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Footwear (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB56A18FE96}" {
   m_sEntityPrefab "{1A912C2A6C8AB6CF}Prefabs/Characters/Footwear/Shoes_ThreeStripe/Shoes_ThreeStripe_White.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB56A18FE93}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB56A18FE91}" {
   m_sEntityPrefab "{D2712ED8A9F3F605}Prefabs/Characters/Footwear/Shoes_ThreeStripe/Shoes_ThreeStripe_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB56A18FE9E}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB56A18FE9F}" {
   m_sEntityPrefab "{726A4FD69B65B517}Prefabs/Characters/Footwear/Boots_Gorka4/Boots_Gorka4.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB56A18FE9C}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}