SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Tshirts (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB621FD407F}" {
   m_sEntityPrefab "{4CF8A04C505CE41B}Prefabs/Characters/Uniforms/Undershirt_VKPO/Undershirt_VKPO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB621FD4061}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB621FD4064}" {
   m_sEntityPrefab "{998D18672DE832E5}Prefabs/Characters/Uniforms/Undershirt_VKPO/Undershirt_VKPO_Desert.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB621FD4065}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB621FD406A}" {
   m_sEntityPrefab "{4598860244EBEAEB}Prefabs/Characters/Uniforms/Shirt_Muscle/Shirt_Muscle_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB621FD406B}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB621FD4068}" {
   m_sEntityPrefab "{4598860244EBEAEB}Prefabs/Characters/Uniforms/Shirt_Muscle/Shirt_Muscle_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB621FE9044}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB621FE9042}" {
   m_sEntityPrefab "{1054238DBE5BBD51}Prefabs/Characters/Uniforms/Shirt_Muscle/Shirt_Muscle_Brown.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB621FEC710}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB621FEC711}" {
   m_sEntityPrefab "{041722C3C8C3ACC9}Prefabs/Characters/Uniforms/Shirt_Muscle/Shirt_Muscle_OD.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB621FEC712}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB621FEC713}" {
   m_sEntityPrefab "{A59622D9D88C0123}Prefabs/Characters/Uniforms/Shirt_Muscle/Shirt_Muscle_Telnyashka.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB621FE7FCB}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB621FE7FB4}" {
   m_sEntityPrefab "{9600A4B797A926A2}Prefabs/Characters/Uniforms/Shirt_TShirt_ION/Shirt_TShirt_ION_RHS.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB621FE7FB5}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB621FE7FB6}" {
   m_sEntityPrefab "{4081352F99AF1486}Prefabs/Characters/Uniforms/Shirt_TShirt/Shirt_TShirt_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB621FF8E7E}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB621FF8E7F}" {
   m_sEntityPrefab "{0AF932067B530166}Prefabs/Characters/Uniforms/Shirt_TShirt/Shirt_TShirt_OD.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB621FF8E78}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB621FF8E79}" {
   m_sEntityPrefab "{F52AA82127D05EDF}Prefabs/Characters/Uniforms/Shirt_Velocity/Shirt_Velocity_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB621FF8E7A}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB621FFDDCC}" {
   m_sEntityPrefab "{DE9FA0D83D6193F9}Prefabs/Characters/Uniforms/Shirt_Velocity/Shirt_Velocity_OD.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB621FFDDC4}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
 }
}