SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Helmets (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB6D7D0D0DC}" {
   m_sEntityPrefab "{A7E6D7ECD5F684D7}Prefabs/Characters/HeadGear/Helmet_SSh68_01/Helmet_SSh68_01.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6D7D0D127}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6D7D0D124}" {
   m_sEntityPrefab "{66196D85AB93D2BE}Prefabs/Characters/HeadGear/Helmet_SSh68_01/Helmet_SSh68_01_camo.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6D7D0D12B}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6D7D0D12A}" {
   m_sEntityPrefab "{D4028ED16DEE99EE}Prefabs/Characters/HeadGear/Helmet_SSh68_01/Helmet_SSh68_01_camonet.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6D7D0D129}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6D7D0D128}" {
   m_sEntityPrefab "{22963D69CA50EB9E}Prefabs/Characters/HeadGear/Helmet_SSh68_01/Helmet_SSh68_01_net.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6D7D05AB1}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6D7D05AB7}" {
   m_sEntityPrefab "{DD35D5EBA6364E77}Prefabs/Characters/HeadGear/Helmet_SSh68_01/Helmet_SSh68_01_cover_KLMK.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6D7D05AB4}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6D7D1B2E2}" {
   m_sEntityPrefab "{12035A212B2BE371}Prefabs/Characters/HeadGear/Helmet_SSh68_01/Helmet_SSh68_01_cover_KLMK_net.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6D7D1B2E3}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6D7D1B2FC}" {
   m_sEntityPrefab "{5F8928B41FB86990}Prefabs/Characters/HeadGear/Helmet_SSh68_01/Helmet_SSh68_01_cover_KZS.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6D7D1B2FB}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6D7D1B2F4}" {
   m_sEntityPrefab "{E49D9EE7E2B3016C}Prefabs/Characters/HeadGear/Helmet_ZSh5_01/Helmet_ZSh5_01.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6D7D1B2F5}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6D7D1B2F6}" {
   m_sEntityPrefab "{BFE3D93AA5B13A89}Prefabs/Characters/HeadGear/Helmet_ZSh7/Helmet_ZSh7V.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6D7D1887C}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}