SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Armbands (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB57693554E}" {
   m_sEntityPrefab "{B0E3787A734D85AC}Prefabs/Characters/Armbands/Single/Factions/Armband_Single_USSR_FriendlyOnly.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB576935548}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB576935557}" {
   m_sEntityPrefab "{07AEEF68955D69AF}Prefabs/Characters/Armbands/Dual/Factions/Armband_Dual_USSR_FriendlyOnly.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB57690CB7A}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB57690CB78}" {
   m_sEntityPrefab "{D4EF091C11CDDF94}Prefabs/Characters/Armbands/Tape/Factions/Armband_Tape_USSR_FriendlyOnly.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB57690CB7F}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB57690CB7E}" {
   m_sEntityPrefab "{5C5A165F517043DA}Prefabs/Characters/Armbands/Tape_Large/Factions/Armband_Tape_Large_USSR_FriendlyOnly.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB57690B1E5}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}