SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Handwear (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB6916704EE}" {
   m_sEntityPrefab "{61C681C29671C273}Prefabs/Characters/Handwear/Gloves_MechanixMpact/Gloves_MechanixMpact_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6916704E9}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6916704F6}" {
   m_sEntityPrefab "{66B75B15AF250BDA}Prefabs/Characters/Handwear/Gloves_MechanixMpact/Gloves_MechanixMpact_Brown.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB691668884}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB691668886}" {
   m_sEntityPrefab "{67D4FA63CF57EB29}Prefabs/Characters/Handwear/Gloves_MechanixMpact/Gloves_MechanixMpact_Covert.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB691668880}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB691668883}" {
   m_sEntityPrefab "{514585D29848282C}Prefabs/Characters/Handwear/Gloves_MechanixMpact/Gloves_MechanixMpact_Coyote.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB691668882}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB69166F2D5}" {
   m_sEntityPrefab "{E59798949E080E70}Prefabs/Characters/Handwear/Gloves_MechanixMpact/Gloves_MechanixMpact_M81_Woodland.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB69166F2DB}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB69166E626}" {
   m_sEntityPrefab "{33066808B3EF4867}Prefabs/Characters/Handwear/Gloves_MechanixMpact/Gloves_MechanixMpact_MC.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB69166E625}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB69166E624}" {
   m_sEntityPrefab "{A9268330530882B9}Prefabs/Characters/Handwear/Gloves_MechanixMpact/Gloves_MechanixMpact_White.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB69166E623}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB69166CB0A}" {
   m_sEntityPrefab "{675B4F093E2485D9}Prefabs/Characters/Handwear/Gloves_MechanixMpact/Gloves_MechanixMpact_WolfGrey.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB69166CB0B}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB69166CB08}" {
   m_sEntityPrefab "{DD417EA38987C9FD}Prefabs/Characters/Handwear/Gloves_Gorka4/Gloves_Gorka4.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6916634F3}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6916634F2}" {
   m_sEntityPrefab "{BC5B532C13965C35}Prefabs/Characters/Handwear/Gloves_Oakley/Gloves_Oakley_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6916634CD}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6916655EC}" {
   m_sEntityPrefab "{1FF0BF59C344BDD3}Prefabs/Characters/Handwear/Gloves_Oakley/Gloves_Oakley_CoyoteBrown.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6916655EB}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB69165EFCA}" {
   m_sEntityPrefab "{AE31F2E542A8E694}Prefabs/Characters/Handwear/Gloves_Oakley/Gloves_Oakley_Khaki.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB69165EFC5}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}