SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Eyewear (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB560BDE0CA}" {
   m_sEntityPrefab "{059BBD768632F474}Prefabs/Characters/Eyewear/npp_kondor/Eyewear_npp_kondor_smoke.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB560BDE0C4}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB560BDE0C2}" {
   m_sEntityPrefab "{11E7A27E17A9198C}Prefabs/Characters/Eyewear/npp_kondor/Eyewear_npp_kondor_olive_smoke.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB560BDE0C1}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB560BDE0C0}" {
   m_sEntityPrefab "{27A692844476B992}Prefabs/Characters/Eyewear/npp_kondor/Eyewear_npp_kondor_tan_smoke.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB560BDE0DF}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}