SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Headgear (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB6D25BAED1}" {
   m_sEntityPrefab "{367BEEE3BE61C597}Prefabs/Characters/HeadGear/Headgear_TSh4/Helmet_tsh4.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6D25BAEDF}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6D25BAED9}" {
   m_sEntityPrefab "{94493910A15ECDC6}Prefabs/Characters/HeadGear/Hat_VKPO_Cap/Hat_VKPO_Cap.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6D25BAED8}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6D25BAEDA}" {
   m_sEntityPrefab "{F5347DE84CA1E3EE}Prefabs/Characters/HeadGear/Hat_VDV_Beret/Hat_VDV_Beret.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6D25B472B}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}