SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Masks (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB56543CA03}" {
   m_sEntityPrefab "{F8554F236521F974}Prefabs/Characters/HeadGear/Headphones/Headphones_6M2/headphones_6m2.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB56543CA1E}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB56543CA1B}" {
   m_sEntityPrefab "{150CBCB5E706F291}Prefabs/Characters/HeadGear/Headphones_6M2/Headphones_6M2-1.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB56543CA1A}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB56543CA19}" {
   m_sEntityPrefab "{52BE66B6E343D441}Prefabs/Characters/HeadGear/Headphones/Headphones_Impact/Headphones_Impact.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB565441871}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB56544187F}" {
   m_sEntityPrefab "{63F1353AF0D18504}Prefabs/Characters/HeadGear/Headphones_Sordin_Liberator/Headphones_Sordin_black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB56544187E}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB56544187D}" {
   m_sEntityPrefab "{2162B5F1B9F5F6BB}Prefabs/Characters/HeadGear/Headphones/Headphones_Sordin_Liberator/Headphones_Sordin_base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB565445680}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB565445681}" {
   m_sEntityPrefab "{85D618A51C013F7A}Prefabs/Characters/HeadGear/Headphones_Peltor/Headphones_Peltor_yellow.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB565448881}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB565448886}" {
   m_sEntityPrefab "{6D6ADA201AD4E09B}Prefabs/Characters/HeadGear/Headphones_Peltor/Headphones_Peltor_olive.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5654488B9}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5654488BF}" {
   m_sEntityPrefab "{EB916F0BF524EF25}Prefabs/Characters/HeadGear/Headphones_Peltor/Headphones_Peltor_black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB565451A66}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB565451A65}" {
   m_sEntityPrefab "{3FDA3C5B74681C25}Prefabs/Characters/HeadGear/Headphones_Sordin_Liberator/Headphones_liberator.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB565451A64}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}