SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Equipment - Medical (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710A20D9D0F2}" {
   m_sEntityPrefab "{A81F501D3EF6F38E}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_US_01.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A20D9D0CB}" {
     m_eItemType HEAL
     m_eItemMode CONSUMABLE
     m_iSupplyCost 0
    }
    SCR_EntityCatalogSupportStationResupplyData "{697D710A20D9D0C5}" {
     m_eResupplyType BANDAGE
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A20D9D0C4}" {
   m_sEntityPrefab "{D70216B1B2889129}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_US_01.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A20D9D0C7}" {
     m_eItemType HEAL
     m_eItemMode CONSUMABLE
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A20D9D0C6}" {
   m_sEntityPrefab "{0D9A5DCF89AE7AA9}Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A20D9D0C1}" {
     m_eItemType HEAL
     m_eItemMode CONSUMABLE
     m_iSupplyCost 0
    }
    SCR_EntityCatalogSupportStationResupplyData "{697D710A20D9E49A}" {
     m_eResupplyType MORPHINE
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A20D9E49B}" {
   m_sEntityPrefab "{5B2FD067D70C1E8F}Prefabs/Items/Medicine/EpinephrineInjection/ACE_Medical_EpinephrineInjection.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A20D9E498}" {
     m_eItemType HEAL
     m_eItemMode CONSUMABLE
     m_iSupplyCost 0
    }
    SCR_EntityCatalogSupportStationResupplyData "{697D710A20D9E499}" {
     m_eResupplyType MORPHINE
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A20D9E486}" {
   m_sEntityPrefab "{00E36F41CA310E2A}Prefabs/Items/Medicine/SalineBag_01/SalineBag_US_01.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A20D9E487}" {
     m_eItemType HEAL
     m_eItemMode CONSUMABLE
     m_iSupplyCost 0
    }
   }
  }
 }
}