SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Equipment - Misc (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710A271DE0D8}" {
   m_sEntityPrefab "{42232FFE6E7AC415}Prefabs/Items/Core/Wirecutters/wirecutters.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A271DE0D2}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A271DE0D1}" {
   m_sEntityPrefab "{B3F2B47340817ED6}Prefabs/Items/ACE_Facepaint_01_US.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A271DE0AE}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A271DE0AF}" {
   m_sEntityPrefab "{CBF9B9942E07B6B8}Prefabs/Items/Equipment/Accessories/ZipCuffs/ACE_Captives_ZipCuffs.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A271DE0AC}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A271DC960}" {
   m_sEntityPrefab "{62F304402A707F68}Prefabs/Items/Equipment/TacticalLadder/ACE_TacticalLadder.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A271DC966}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A271DC967}" {
   m_sEntityPrefab "{452112928EC197AD}Prefabs/Items/Equipment/Periscope/ACE_TacticalPeriscope.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A271DAB71}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A271DAB72}" {
   m_sEntityPrefab "{B70756E9489B011A}Prefabs/Items/Equipment/WeatherMeter/WeatherMeter_Kestrel4500/WeatherMeter_Kestrel4500.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A271D599A}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}