SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Deployable Parts (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB65F437CA9}" {
   m_sEntityPrefab "{07BC23F8D9223863}Prefabs/Items/Misc/Sandbags/Part_Sandbag_Burlap.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB65F437D53}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB65F437D50}" {
   m_sEntityPrefab "{B623482E2704B69A}Prefabs/Weapons/Attachments/Optics/Scopes/Optic_SPP/Optic_SPP.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB65F437D5F}" {
     m_eItemType MORTARS
     m_eItemMode ATTACHMENT
     m_iSupplyCost 50
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB65F437D5E}" {
   m_sEntityPrefab "{184DFCEFE574E775}Prefabs/Items/Equipment/Tripods/6T7/Part_NSV_Gun.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB65F437D5D}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 80
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB65F42CEA3}" {
   m_sEntityPrefab "{184DFCEFE574E776}Prefabs/Items/Equipment/Tripods/6T7/Part_NSV_Tripod.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB65F42CEA2}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 40
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB65F42CEA5}" {
   m_sEntityPrefab "{4323046B2CC94818}Prefabs/Items/Equipment/Mortars/2B14/Part_2B14_BasePlate.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB65F42CEA4}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 90
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB65F42CEA7}" {
   m_sEntityPrefab "{00B1E3F86A9EF45D}Prefabs/Items/Equipment/Mortars/2B14/Part_2B14_Bipod.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB65F42CEA6}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 90
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB65F42C5B6}" {
   m_sEntityPrefab "{F62E5FBCD723FF73}Prefabs/Items/Equipment/Mortars/2B14/Part_2B14_Barrel.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB65F42C5AF}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 90
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB65F42C5AE}" {
   m_sEntityPrefab "{F6490587042BFEE5}Prefabs/Items/Equipment/Tripods/PKM/Part_Tripod_6T5.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB65F42C5A1}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 30
     m_eRequiredRank CORPORAL
    }
   }
  }
 }
}