SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Bipods (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710A9F0D990F}" {
   m_sEntityPrefab "{DA6F4469427F6128}Prefabs/Weapons/Attachments/Foregrips/L85_Grip_Pod/Grip_Pod_base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A9F0D9908}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}