SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Optics (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710A8E83B1A7}" {
   m_sEntityPrefab "{D2018EDB1BBF4C88}Prefabs/Weapons/Attachments/Optics/Scopes/Optic_ARTII/Optic_ARTII.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A8E83B1A0}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A8E83B1BF}" {
   m_sEntityPrefab "{78E6C499CFFB8882}Prefabs/Weapons/Attachments/Optics/Optic_ARTII/Optic_ARTII_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A8E83B1BC}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A8E83B1BD}" {
   m_sEntityPrefab "{304664561B760EE0}Prefabs/Weapons/Attachments/Optics/Optic_ARTII/Optic_ARTII_OliveGreen_Sand_Stripes_Wrapped.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A8E8373F7}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A8E8373F1}" {
   m_sEntityPrefab "{BD496EE1B40DC510}Prefabs/Weapons/Attachments/Optics/Scopes/Optic_4x20/Optic_4x20.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A8E8373F2}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A8E8373F3}" {
   m_sEntityPrefab "{44AAA61117B6CA8E}Prefabs/Weapons/Attachments/Optics/Optic_4x20/Optic_4x20_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A8E8373FC}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A8E8373FD}" {
   m_sEntityPrefab "{B9773AC7CCDAD633}Prefabs/Weapons/Attachments/Optics/Optic_4x20/Optic_4x20_OliveGreen_Solid.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A8E8373FE}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A8E833671}" {
   m_sEntityPrefab "{08286DDBB1F33FF1}Prefabs/Weapons/Attachments/Optics/Scopes/Optic_AP2k/Collim_AP2k.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A8E83364B}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A8E83364A}" {
   m_sEntityPrefab "{519E60CCCDCA456A}Prefabs/Weapons/Attachments/Optics/Optic_AP2k/Collim_AP2k_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A8E833649}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A8E833648}" {
   m_sEntityPrefab "{B8764E1CDC4F4F22}Prefabs/Weapons/Attachments/Optics/Optic_AP2k/Collim_AP2k_OliveGreen_Solid.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A8E8308B0}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}