SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Tactical (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710AA3C55150}" {
   m_sEntityPrefab "{0FFFB0BCE1A21A2E}Prefabs/Weapons/Attachments/Lasers/anpeq16/Laser_ANPEQ16.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AA3C55156}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AA3C55148}" {
   m_sEntityPrefab "{5AE8F3A22BDB534F}Prefabs/Weapons/Attachments/Lasers/anpeq15/Laser_ANPEQ15_black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AA3C5514B}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AA3C5514A}" {
   m_sEntityPrefab "{9A185BC14F1166B4}Prefabs/Weapons/Attachments/Lasers/anpeq15/Laser_ANPEQ15_tan.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AA3C5514D}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AA3C5514C}" {
   m_sEntityPrefab "{CB8AB382E3F45336}Prefabs/Weapons/Attachments/Lasers/perst_classic/Laser_perst_classic_base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AA3C5514F}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AA3C5514E}" {
   m_sEntityPrefab "{A7C848BABE4F4577}Prefabs/Weapons/Attachments/Lasers/psq23/LaserRangefinder_PSQ23_base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AA3C5C025}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AA3C5C02B}" {
   m_sEntityPrefab "{5C00FABD6129BE79}Prefabs/Weapons/Attachments/Lights/Light_klesh2_base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AA3C5BC4A}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AA3C5BC49}" {
   m_sEntityPrefab "{D9887A041DA4D6C9}Prefabs/Weapons/Attachments/Lights/Light_su233_base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AA3C5BC48}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AA3C5BC4F}" {
   m_sEntityPrefab "{C32EC74B4B0C8CA1}Prefabs/Weapons/Attachments/Lights/Light_m300c_blk.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AA3C470C3}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AA3C470C2}" {
   m_sEntityPrefab "{005374A5149FAC4F}Prefabs/Weapons/Attachments/Lights/Light_m300c_tan.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AA3C470C1}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AA3C470C0}" {
   m_sEntityPrefab "{04332BCD7FF84920}Prefabs/Weapons/Attachments/Lights/Light_wml_blk.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AA3C412C9}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AA3C412B6}" {
   m_sEntityPrefab "{C74E9823206B69CE}Prefabs/Weapons/Attachments/Lights/Light_wml_tan.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AA3C412B0}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}