SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Iron Sights (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710A87609790}" {
   m_sEntityPrefab "{6B164FDCD50633AC}Prefabs/Weapons/Attachments/Optics/lmt_l8a/lmt_l8a_rear.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A87609796}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A8760978B}" {
   m_sEntityPrefab "{BC01D4724626132E}Prefabs/Weapons/Attachments/Optics/kac_folding_sights_600/kac_folding_sight_front.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A8760978A}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A8760978D}" {
   m_sEntityPrefab "{41F3C10C4FEBC1FF}Prefabs/Weapons/Attachments/Optics/kac_folding_sights_600/kac_folding_sight_600_rear.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A8760978C}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A87612B79}" {
   m_sEntityPrefab "{B05910AE5C2526DD}Prefabs/Weapons/Attachments/Optics/mbus/mbus_blk_folding_sight_front.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A87612B7B}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A87612B74}" {
   m_sEntityPrefab "{677E8A0792696783}Prefabs/Weapons/Attachments/Optics/mbus/mbus_blk_folding_sight_rear.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A87612B75}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A8761B1C7}" {
   m_sEntityPrefab "{CEF0704C814E32C5}Prefabs/Weapons/Attachments/Optics/mbus/mbus_tan_folding_sight_front.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A8761B1C4}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A8761B1C5}" {
   m_sEntityPrefab "{9ECBF331E7F6EED3}Prefabs/Weapons/Attachments/Optics/mbus/mbus_tan_folding_sight_rear.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A87619290}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}