SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Suppressors (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710ABC7B319F}" {
   m_sEntityPrefab "{022A63F2857F6CE4}Prefabs/Weapons/Attachments/Muzzle/556x45/Suppressor_KAC_NT4.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ABC7B3199}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ABC7B3197}" {
   m_sEntityPrefab "{7DA560AE5E018076}Prefabs/Weapons/Attachments/Muzzle/556x45/Suppressor_KAC_NT4_Cover.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ABC7B3194}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ABC7B3192}" {
   m_sEntityPrefab "{63F743C4574EC229}Prefabs/Weapons/Attachments/Muzzle/556x45/Suppressor_KAC_NT4_CoverMC.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ABC7B3193}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ABC7B3190}" {
   m_sEntityPrefab "{BBA0751BBD4C6F23}Prefabs/Weapons/Attachments/Muzzle/556x45/BlastRegulator_SurefireWarden_base.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ABC7B3191}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ABC7B6EB2}" {
   m_sEntityPrefab "{D859B82903DF4532}Prefabs/Weapons/Attachments/Muzzle/556x45/BlastRegulator_SurefireWarden_FDE.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ABC7B6F4C}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ABC7AC28F}" {
   m_sEntityPrefab "{05D8008A7A689D2A}Prefabs/Weapons/Attachments/Muzzle/556x45/Suppressor_RC2_556_Base.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ABC7AC28C}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ABC7AC28D}" {
   m_sEntityPrefab "{592DF768C2903A6C}Prefabs/Weapons/Attachments/Muzzle/556x45/Suppressor_RC2_556_FDE.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ABC7AC28A}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ABC7AC282}" {
   m_sEntityPrefab "{0379B66FFAED8072}Prefabs/Weapons/Attachments/Muzzle/556x45/Suppressor_SurefireRC3_base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ABC7AD64A}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ABC7AD64B}" {
   m_sEntityPrefab "{AE4C0DCCD57B11B1}Prefabs/Weapons/Attachments/Muzzle/556x45/Suppressor_SurefireRC3_FDE.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ABC7AD648}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ABC7A17BF}" {
   m_sEntityPrefab "{598FDD04ECFBD77D}Prefabs/Weapons/Attachments/Muzzle/762x51/Suppressor_FA762SS_base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ABC7A17BE}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ABC7A17A1}" {
   m_sEntityPrefab "{3756AA17E035BBF8}Prefabs/Weapons/Attachments/Muzzle/762x51/Suppressor_FA762SS_FDE.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ABC798EFD}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}