SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Muzzle (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710A8886A58C}" {
   m_sEntityPrefab "{D09785FD7DBEBB2B}Prefabs/Weapons/Attachments/Muzzle/556x45/FlashHider_M16_base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A8886A591}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}