SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Iron Sights (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710A86F0B1FC}" {
   m_sEntityPrefab "{3E1ACE295E9520CE}Prefabs/Weapons/Attachments/Optics/IronSights/KAC_Front_Sight.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A86F0B1F6}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A86F0B18B}" {
   m_sEntityPrefab "{2ED8374B31DCAFA7}Prefabs/Weapons/Attachments/Optics/IronSights/KAC_Rear_Sight.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A86F0B18A}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A86F0B189}" {
   m_sEntityPrefab "{B4559C0178EA6F6F}Prefabs/Weapons/Attachments/Optics/IronSights/KAC_Front_Sight_FDE.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A86F0B188}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A86F0B18F}" {
   m_sEntityPrefab "{5C0414D064815A96}Prefabs/Weapons/Attachments/Optics/IronSights/KAC_Rear_Sight_FDE.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A86F0A3E9}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A86F0A3EB}" {
   m_sEntityPrefab "{B108C2AAA4A7E674}Prefabs/Weapons/Attachments/Irons/MPX_Front_Sight.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A86EF3777}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A86EF3776}" {
   m_sEntityPrefab "{B4D065D5D0841F24}Prefabs/Weapons/Attachments/Irons/MPX_Rear_Sight.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A86EF3779}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A86EF3778}" {
   m_sEntityPrefab "{BE5C648DB6A07577}Prefabs/Weapons/Attachments/Irons/G28_Rear_Sight.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A86EF377E}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A86EF8875}" {
   m_sEntityPrefab "{A20F48CE1F479982}Prefabs/Weapons/Attachments/Irons/L85_Iron_Carryhandle.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A86EF886A}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A86EF886B}" {
   m_sEntityPrefab "{9F7C660D3CD4A343}Prefabs/Weapons/Attachments/Irons/M16A4_Carryhandle.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A86EFA833}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}