SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Suppressors (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710ABA58FA11}" {
   m_sEntityPrefab "{2CDCFF4237E63650}Prefabs/Weapons/Attachments/Muzzle/556x45/Suppressor_M16.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ABA58FAEB}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ABA58FAE9}" {
   m_sEntityPrefab "{C374AF8B50B0C6F0}Prefabs/Weapons/Attachments/Muzzle/556x45/Suppressor_M16_OliveGreen_Solid.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ABA58FAE6}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ABA58FAE7}" {
   m_sEntityPrefab "{ADDF08D09F1877A5}Prefabs/Weapons/Attachments/Muzzle/556x45/Suppressor_M16_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ABA58FAE4}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}