SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Explosives - C4 (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710A5164CDCD}" {
   m_sEntityPrefab "{33CBDE73AB48172A}Prefabs/Weapons/Explosives/DemoBlock_M112/DemoBlock_M112.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A5164CDF3}" {
     m_eItemType EXPLOSIVES
     m_iSupplyCost 10
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A5164CDF4}" {
   m_sEntityPrefab "{CE0AF733722B3978}Prefabs/Items/Equipment/Detonators/BlastingMachine_M34/BlastingMachine_M34.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A516316FD}" {
     m_eItemType EXPLOSIVES
     m_iSupplyCost 10
    }
   }
  }
 }
}