SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Explosives - Mortars (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710A522FFDD9}" {
   m_sEntityPrefab "{6113990D163E5249}Prefabs/Items/Equipment/BallisticTable/BallisticTable_US.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A522FFDDF}" {
     m_eItemType MORTARS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A522FFDD0}" {
   m_sEntityPrefab "{3D5594CC62AAFB88}Prefabs/Props/Military/AmmoBoxes/AmmoBox_81mm_mortar_3rnd.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A522FAE32}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 5
     m_aArsenalAlternativeCostData {
      SCR_ArsenalAlternativeCostSellAmountData "{697D710A522FAE30}" {
       m_eAlternativeCostType DEFAULT
       m_iSupplyCost 5
       m_iSupplyRefundAmount 5
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A522FAE37}" {
   m_sEntityPrefab "{38BAE094333E31BF}Prefabs/Weapons/Ammo/Ammo_Shell_81mm_HE_M821.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A522FAE36}" {
     m_eItemType MORTARS
     m_eItemMode AMMUNITION
     m_iSupplyCost 20
    }
    SCR_EntityCatalogSupportStationResupplyData "{697D710A522FAE35}" {
     m_eResupplyType MORTAR_SHELL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A522FAE34}" {
   m_sEntityPrefab "{DD2065AE34D8DFA9}Prefabs/Weapons/Ammo/Ammo_Shell_81mm_Illum_M853A1.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A522FAE2B}" {
     m_eItemType MORTARS
     m_eItemMode AMMUNITION
     m_iSupplyCost 5
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A522FAE2A}" {
   m_sEntityPrefab "{F7807293E94D3C88}Prefabs/Weapons/Ammo/Ammo_Shell_81mm_Smoke_M819.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A522F016A}" {
     m_eItemType MORTARS
     m_eItemMode AMMUNITION
     m_iSupplyCost 5
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A522F0169}" {
   m_sEntityPrefab "{DD6844AB03FDA84F}Prefabs/Weapons/Ammo/Ammo_Shell_81mm_Practice_M879.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A522F0168}" {
     m_eItemType MORTARS
     m_eItemMode AMMUNITION
     m_iSupplyCost 1
    }
   }
  }
 }
}