SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Deployable Parts (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710A3D37C0B6}" {
   m_sEntityPrefab "{1742632597955A55}Prefabs/Items/Misc/Sandbags/Part_Sandbag_Plastic.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A3D37C0B0}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A3D37C0AF}" {
   m_sEntityPrefab "{9B625CAE6DEE1DAB}Prefabs/Items/Equipment/Tripods/M2/Part_M2_Gun.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A3D37C0AD}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 80
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A3D37C0AA}" {
   m_sEntityPrefab "{6A3EF260029FE220}Prefabs/Items/Equipment/Tripods/M2/Part_M3_Tripod.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A3D37C0AB}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 40
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A3D37FF37}" {
   m_sEntityPrefab "{0D540E16A6E53433}Prefabs/Items/Equipment/Mortars/M252/Part_M252_BasePlate.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A3D37FF35}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 90
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A3D37FF3A}" {
   m_sEntityPrefab "{80D38046CB4D4663}Prefabs/Items/Equipment/Mortars/M252/Part_M252_Bipod.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A3D37FF3B}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 90
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A3D367543}" {
   m_sEntityPrefab "{62B704DD79A3B5BE}Prefabs/Items/Equipment/Mortars/M252/Part_M252_Barrel.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A3D367540}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 90
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A3D36D497}" {
   m_sEntityPrefab "{EF55A296E50DC8B8}Prefabs/Items/Equipment/Tripods/M60/Part_Tripod_M122.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A3D36D4EC}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 30
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A3D36D4EF}" {
   m_sEntityPrefab "{88CC9E80A955B22A}Prefabs/Weapons/Attachments/Optics/MDO/Part_Optic_MDO_M2HB.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A3D36D4EE}" {
     m_eItemType MORTARS
     m_eItemMode ATTACHMENT
     m_iSupplyCost 50
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A3D36D4E9}" {
   m_sEntityPrefab "{50A9968677B293A9}Prefabs/Weapons/Attachments/Optics/pas13g/Part_Optic_PAS13G_M2HB.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A3D36D4E8}" {
     m_eItemType MORTARS
     m_eItemMode ATTACHMENT
     m_iSupplyCost 50
     m_eRequiredRank SERGEANT
    }
   }
  }
 }
}