SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Throwables - Stun (Bacon)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB78FE652CF}" {
   m_sEntityPrefab "{8E97135D2E37CAA6}Prefabs/Weapons/Grenades/Grenade_Stun_OPFOR.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB78FE652C9}" {
     m_eItemType NON_LETHAL_THROWABLE
     m_iSupplyCost 5
    }
   }
  }
 }
}