SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Throwables - Flares (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB788558B04}" {
   m_sEntityPrefab "{327103CB218E7CA1}Prefabs/Weapons/Flares/Flare_RSP30_white.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB788558B1E}" {
     m_eItemType NON_LETHAL_THROWABLE
     m_iSupplyCost 10
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB788558B1C}" {
   m_sEntityPrefab "{36218D5F0C7095E6}Prefabs/Weapons/Flares/Flare_RSP30_red.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB788558B1B}" {
     m_eItemType NON_LETHAL_THROWABLE
     m_iSupplyCost 10
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB788558B1A}" {
   m_sEntityPrefab "{FC79F6BDEB7F1BC2}Prefabs/Weapons/Flares/Flare_RSP30_green.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB788558B19}" {
     m_eItemType NON_LETHAL_THROWABLE
     m_iSupplyCost 10
    }
   }
  }
 }
}