SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Hidden - Not In Arsenal (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB78011E2CB}" {
   m_sEntityPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et"
   m_aEntityDataList {
    SCR_NonArsenalItemCostCatalogData "{697D7DB78011E531}" {
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB78011E533}" {
   m_sEntityPrefab "{922F95F91943F69A}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded_US.et"
   m_aEntityDataList {
    SCR_NonArsenalItemCostCatalogData "{697D7DB7801159C1}" {
     m_iSupplyCost 0
    }
   }
  }
 }
}