SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Throwables - Smoke (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710A442285A2}" {
   m_sEntityPrefab "{9DB69176CEF0EE97}Prefabs/Weapons/Grenades/Smoke_ANM8HC.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A442285A4}" {
     m_eItemType NON_LETHAL_THROWABLE
     m_iSupplyCost 10
    }
    SCR_EntityCatalogSupportStationResupplyData "{697D710A442285AA}" {
     m_eResupplyType SMOKE
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A442285A8}" {
   m_sEntityPrefab "{D41D22DD1B8E921E}Prefabs/Weapons/Grenades/M18/Smoke_M18_Green.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A442285A9}" {
     m_eItemType NON_LETHAL_THROWABLE
     m_iSupplyCost 10
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A442285AE}" {
   m_sEntityPrefab "{3343A055A83CB30D}Prefabs/Weapons/Grenades/M18/Smoke_M18_Red.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A442285AF}" {
     m_eItemType NON_LETHAL_THROWABLE
     m_iSupplyCost 10
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A442285AC}" {
   m_sEntityPrefab "{14C1A0F061D9DDEE}Prefabs/Weapons/Grenades/M18/Smoke_M18_Violet.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A44222DEE}" {
     m_eItemType NON_LETHAL_THROWABLE
     m_iSupplyCost 10
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A44222DF0}" {
   m_sEntityPrefab "{9BBDEE253A16CC66}Prefabs/Weapons/Grenades/M18/Smoke_M18_Yellow.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A44222DF1}" {
     m_eItemType NON_LETHAL_THROWABLE
     m_iSupplyCost 10
    }
   }
  }
 }
}