SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Throwables - Flares (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710A43D67B38}" {
   m_sEntityPrefab "{EC9BDA3D9DDD8795}Prefabs/Weapons/Flares/FlareStarParachute_M127A1_white.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A43D67BC2}" {
     m_eItemType NON_LETHAL_THROWABLE
     m_iSupplyCost 10
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A43D67BC0}" {
   m_sEntityPrefab "{756231FF84F158A4}Prefabs/Weapons/Flares/FlareStarParachute_M126A1_red.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A43D67BC1}" {
     m_eItemType NON_LETHAL_THROWABLE
     m_iSupplyCost 10
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A43D67BC6}" {
   m_sEntityPrefab "{51D9E3AEC8476BA4}Prefabs/Weapons/Flares/FlareStarParachute_M195_green.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A43D67BC7}" {
     m_eItemType NON_LETHAL_THROWABLE
     m_iSupplyCost 10
    }
   }
  }
 }
}