SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Throwables - Stun (Bacon)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710A473BC0B7}" {
   m_sEntityPrefab "{ED97A510AA0A46C5}Prefabs/Weapons/Grenades/Grenade_Stun.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A473BC0BC}" {
     m_eItemType NON_LETHAL_THROWABLE
     m_iSupplyCost 5
    }
   }
  }
 }
}