SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{697B6CB98C413134}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{697B6CB98C41313C}" {
     m_aEntityDataList {
      SCR_EntityCatalogLoadoutData "{697B6CB98C41313F}" {
       m_eRequiredRank RENEGADE
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{697B6CB98C413139}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{697B6CB98C413138}" {
     m_aEntityDataList {
      SCR_EntityCatalogLoadoutData "{697B6CB98C417CF5}" {
       m_eRequiredRank RENEGADE
      }
     }
    }
    SCR_EntityCatalogEntry "{697B6CB98C417CF7}" {
     m_aEntityDataList {
      SCR_EntityCatalogLoadoutData "{697B6CB98C40BB0C}" {
       m_eRequiredRank RENEGADE
      }
     }
    }
   }
  }
 }
}