SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{605697836F02AFD9}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{64F0B8D9CBA5FF38}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64F0B8D9C8B18EEE}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{69DE97E1D59937F4}" {
     m_bEnabled 0
    }
   }
  }
 }
}