SCR_EntityCatalog {
 m_eEntityCatalogType WEAPONS_TRIPOD
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{68E338471439CF88}" {
   m_sEntityPrefab "{723870DBB19D30B0}Prefabs/Weapons/Tripods/Tripod_6T5_PKM.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68E338471439CF74}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{68E338471439CF75}" {
   m_sEntityPrefab "{29F0CC704A582154}Prefabs/Weapons/Tripods/6T7/Tripod_6T7_NSV.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68E338471439CF72}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{68E338471439CF73}" {
   m_sEntityPrefab "{3EA26CFD7A202636}Prefabs/Weapons/Tripods/6T7/Tripod_6T7_NSV_SPP.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68E338471439CF70}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{68E33847143991F2}" {
   m_sEntityPrefab "{D1FFE458E8AC4BDB}Prefabs/Weapons/Mortars/2B14/Mortar_2B14_hand.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{68E33847143991F3}" {
    }
   }
  }
 }
}