SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Equipment - Misc (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB6495B8359}" {
   m_sEntityPrefab "{42232FFE6E7AC415}Prefabs/Items/Core/Wirecutters/wirecutters.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6495B8353}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6495B8351}" {
   m_sEntityPrefab "{28FA34E692783ACB}Prefabs/Items/ACE_Facepaint_01_USSR.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6495B832E}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6495B832F}" {
   m_sEntityPrefab "{CBF9B9942E07B6B8}Prefabs/Items/Equipment/Accessories/ZipCuffs/ACE_Captives_ZipCuffs.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6495B832C}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6495BA7AB}" {
   m_sEntityPrefab "{62F304402A707F68}Prefabs/Items/Equipment/TacticalLadder/ACE_TacticalLadder.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6495BA7AA}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6495BA7AC}" {
   m_sEntityPrefab "{452112928EC197AD}Prefabs/Items/Equipment/Periscope/ACE_TacticalPeriscope.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6495BD93E}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB6495BD93C}" {
   m_sEntityPrefab "{B70756E9489B011A}Prefabs/Items/Equipment/WeatherMeter/WeatherMeter_Kestrel4500/WeatherMeter_Kestrel4500.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB6495BD933}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}