SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Equipment - NVGs (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB64A54E2BF}" {
   m_sEntityPrefab "{6EA1508D0D40BECC}Prefabs/Items/Equipment/NVG/GPNVG18/NVG_GPNVG18_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB64A54E2B5}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
     m_eRequiredRank CAPTAIN
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB64A54E2A8}" {
   m_sEntityPrefab "{F212BC428F90B250}Prefabs/Items/Equipment/NVG/GPNVG18/NVG_GPNVG18_Black_WP.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB64A54425D}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
     m_eRequiredRank CAPTAIN
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB64A54425F}" {
   m_sEntityPrefab "{9860F1A055A7F8D2}Prefabs/Items/Equipment/NVG/GPNVG18/NVG_GPNVG18_Black_Amber.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB64A54425E}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
     m_eRequiredRank CAPTAIN
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB64A544259}" {
   m_sEntityPrefab "{3A8189F178FE89FF}Prefabs/Items/Equipment/NVG/GPNVG18/NVG_GPNVG18_FDE.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB64A559077}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
     m_eRequiredRank CAPTAIN
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB64A559076}" {
   m_sEntityPrefab "{C4064D19F46859C7}Prefabs/Items/Equipment/NVG/GPNVG18/NVG_GPNVG18_FDE_WP.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB64A559075}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
     m_eRequiredRank CAPTAIN
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB64A559074}" {
   m_sEntityPrefab "{9EF65B2313940763}Prefabs/Items/Equipment/NVG/GPNVG18/NVG_GPNVG18_FDE_Amber.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB64A550F2B}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
     m_eRequiredRank CAPTAIN
    }
   }
  }
 }
}