SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Hidden - Not In Arsenal (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710A5651B45B}" {
   m_sEntityPrefab "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et"
   m_aEntityDataList {
    SCR_NonArsenalItemCostCatalogData "{697D710A5651B45D}" {
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A5651B453}" {
   m_sEntityPrefab "{F849217AB3BA88BE}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded_USSR.et"
   m_aEntityDataList {
    SCR_NonArsenalItemCostCatalogData "{697D710A56502A79}" {
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A56502A7B}" {
   m_sEntityPrefab "{43FDAF3FA0FF2299}Prefabs/Weapons/Attachments/Underbarrel/UGL_M203_long.et"
   m_aEntityDataList {
    SCR_NonArsenalItemCostCatalogData "{697D710A5650E3AB}" {
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A5650E3AA}" {
   m_sEntityPrefab "{775E9992AF575338}Prefabs/Weapons/Attachments/Underbarrel/UGL_M203_long_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_NonArsenalItemCostCatalogData "{697D710A5650E3AD}" {
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A5650E3AC}" {
   m_sEntityPrefab "{6DE8BD5167F90D6D}Prefabs/Weapons/Attachments/Underbarrel/UGL_M203_long_OliveGreen_Solid.et"
   m_aEntityDataList {
    SCR_NonArsenalItemCostCatalogData "{697D710A5650DD6F}" {
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A5650DD6C}" {
   m_sEntityPrefab "{AB268D088F2D6291}Prefabs/Weapons/Attachments/Underbarrel/UGL_M203_short.et"
   m_aEntityDataList {
    SCR_NonArsenalItemCostCatalogData "{697D710A5650DD6D}" {
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A5650D88A}" {
   m_sEntityPrefab "{D711F819F3271AC6}Prefabs/Weapons/Attachments/Underbarrel/UGL_M203_short_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_NonArsenalItemCostCatalogData "{697D710A5650D895}" {
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A5650D894}" {
   m_sEntityPrefab "{49CC4426C8671477}Prefabs/Weapons/Attachments/Underbarrel/UGL_M203_short_OliveGreen_Solid.et"
   m_aEntityDataList {
    SCR_NonArsenalItemCostCatalogData "{697D710A5650D89D}" {
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A565378A8}" {
   m_sEntityPrefab "{1ABABE3551512B0A}Prefabs/Weapons/Attachments/Underbarrel/UGL_GP25.et"
   m_aEntityDataList {
    SCR_NonArsenalItemCostCatalogData "{697D710A565378A9}" {
     m_iSupplyCost 0
    }
   }
  }
 }
}