SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Armbands (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710AAD9F2D9D}" {
   m_sEntityPrefab "{FC9086A2DD5516E9}Prefabs/Characters/Armbands/Single/Factions/Armband_Single_US_FriendlyOnly.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AAD9F2D86}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AAD9F2D85}" {
   m_sEntityPrefab "{1AD1E9864A628BA4}Prefabs/Characters/Armbands/Dual/Factions/Armband_Dual_US_FriendlyOnly.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AAD9F2D82}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AAD9F2D83}" {
   m_sEntityPrefab "{F6F59002B9BE2D47}Prefabs/Characters/Armbands/Tape/Factions/Armband_Tape_US_FriendlyOnly.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AAD9FE6EE}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AAD9FE6EC}" {
   m_sEntityPrefab "{311BC444A244B7B3}Prefabs/Characters/Armbands/Tape_Large/Factions/Armband_Tape_Large_US_FriendlyOnly.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AAD9FCD2D}" {
     m_eItemType HANDWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}