SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Eyewear (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710AC032A878}" {
   m_sEntityPrefab "{E2AEE09BA445A688}Prefabs/Characters/Eyewear/npp_kondor/Eyewear_npp_kondor.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AC032A841}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AC032A84F}" {
   m_sEntityPrefab "{712F76DA44136525}Prefabs/Characters/Eyewear/npp_kondor/Eyewear_npp_kondor_olive.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AC032A84E}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AC032A84D}" {
   m_sEntityPrefab "{31C47FFE2E732C4D}Prefabs/Characters/Eyewear/npp_kondor/Eyewear_npp_kondor_tan.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AC032A84C}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AC032A84B}" {
   m_sEntityPrefab "{2934192D7BA3465E}Prefabs/Characters/Eyewear/gascan/Eyewear_gascan.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AC03D6F6F}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AC03D6F6D}" {
   m_sEntityPrefab "{79A869C91A7A1368}Prefabs/Characters/Eyewear/gascan/Eyewear_gascan_Blk.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AC03DD3BB}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AC03DD3BA}" {
   m_sEntityPrefab "{BA0AD5FBC86E88D3}Prefabs/Characters/Eyewear/crossbow/Eyewear_ess_crossbow.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AC03DD3A5}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AC03D8BF0}" {
   m_sEntityPrefab "{608F66AB8B36B85D}Prefabs/Characters/Eyewear/crossbow/Eyewear_ess_crossbow_blk.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AC03D8BF1}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AC03D8BF2}" {
   m_sEntityPrefab "{F3672F802360D2E4}Prefabs/Characters/Eyewear/crossbow/Eyewear_ess_crossbow_blk_clr.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AC03D8BF3}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AC03D8AAC}" {
   m_sEntityPrefab "{D4ABE8F396146587}Prefabs/Characters/Eyewear/crossbow/Eyewear_ess_crossbow_clr.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AC03D8AAB}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AC03D8AAA}" {
   m_sEntityPrefab "{9C030889E9A05770}Prefabs/Characters/Eyewear/npp_strelok/Eyewear_npp_strelok.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AC03D8AA9}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AC03DB5E3}" {
   m_sEntityPrefab "{0A6931140B34A0FE}Prefabs/Characters/Eyewear/npp_strelok/Eyewear_npp_strelok_tor.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AC03DB5E8}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}