SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Boonies (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710ADB456A1C}" {
   m_sEntityPrefab "{E12126CDE731EED5}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/Hat_Boonie_US_01.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADB456A1A}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ADB456A14}" {
   m_sEntityPrefab "{8D75122D5BF561FB}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/Hat_Boonie_US_olive.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADB456A15}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ADB456A16}" {
   m_sEntityPrefab "{19231774D1D67091}Prefabs/Characters/HeadGear/Hat_Boonie_US_01/Hat_Boonie_US_TigerStripe.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADB456A17}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}