SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Footwear (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710AF2E5DBF1}" {
   m_sEntityPrefab "{320FA1CD5B1D5601}Prefabs/Characters/Footwear/Boots_USMC_Combat/Footwear_USMC_Combat.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AF2E5DBFF}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AF2E5DBF8}" {
   m_sEntityPrefab "{21B331B5FA807997}Prefabs/Characters/Footwear/Boots_Rocky_SV2/Footwear_Rocky_SV2.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AF2E5DBFB}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AF2E5DBFA}" {
   m_sEntityPrefab "{4738D761E82062D2}Prefabs/Characters/Footwear/Boots_Rocky_SV2/Boots_Rocky_SV2_Black.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AF2E5DBE5}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AF2E5055E}" {
   m_sEntityPrefab "{934C7275AC865817}Prefabs/Characters/Footwear/Boots_BCT/Footwear_BCT.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AF2E5055C}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AF2E5055D}" {
   m_sEntityPrefab "{26E618F9E0E12F18}Prefabs/Characters/Footwear/Boots_Luma/Boots_Luma_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AF2E56628}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AF2E5662F}" {
   m_sEntityPrefab "{E1DAD298C9D74234}Prefabs/Characters/Footwear/Boots_Luma/Boots_Luma_Gray.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AF2E4E52B}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AF2E4E52A}" {
   m_sEntityPrefab "{1048F0A85D78D6DE}Prefabs/Characters/Footwear/Boots_Luma/Boots_Luma_OD.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AF2E4E529}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AF2E4E528}" {
   m_sEntityPrefab "{057E63449502EBCA}Prefabs/Characters/Footwear/Boots_Salomon/Footwear_Salomon.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AF2E4E527}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AF2E4E526}" {
   m_sEntityPrefab "{64B94D8A4D92A4BD}Prefabs/Characters/Footwear/Boots_Altama/Footwear_Altama.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AF2E4C8EC}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AF2E4C8EF}" {
   m_sEntityPrefab "{660952F979E8EBF2}Prefabs/Characters/Footwear/Boots_solomon_ultra_x/Footwear_Altama_Boots.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AF2E4443E}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}