SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Footwear (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710AF48F36A1}" {
   m_sEntityPrefab "{14A3D415E46BCD59}Prefabs/Characters/Footwear/Boots_Jungle/Boots_Jungle_Green.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AF48F36AE}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AF48F36A9}" {
   m_sEntityPrefab "{A39CD33E1EE6F6BA}Prefabs/Characters/Footwear/Boots_Jungle/Boots_Jungle_VZ95.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AF48F36AA}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AF48F36AB}" {
   m_sEntityPrefab "{68029AF966E46794}Prefabs/Characters/Footwear/Boots_DEFCON/Boots_DEFCON.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AF48F36B4}" {
     m_eItemType FOOTWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}