SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Helmets (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710AE4BBD00B}" {
   m_sEntityPrefab "{D34E69F46D5E5819}Prefabs/Characters/HeadGear/Helmets/Helmet_Devtac_Ronin/Helmet_Devtac_Ronin.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AE4BBD00E}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AE4BBD013}" {
   m_sEntityPrefab "{242651B5C13B706D}Prefabs/Characters/HeadGear/Helmets/Helmet_Devtac_Skull/Helmet_Devtac_Skull.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AE4BBD012}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}