SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Boonies (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710ADD348D31}" {
   m_sEntityPrefab "{06A1542E38472C0A}Prefabs/Characters/HeadGear/Hats/Hat_Boonie_RHS/Hat_Boonie_RHS_MARPAT_Desert.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADD348DCF}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ADD348DC9}" {
   m_sEntityPrefab "{49D7D9FEB06E8F6C}Prefabs/Characters/HeadGear/Hats/Hat_Boonie_RHS/Hat_Boonie_RHS_MARPAT_Woodland.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADD348DCA}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}