SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Backpacks (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710AAFD205F4}" {
   m_sEntityPrefab "{9B6B61BB3FE3DFB0}Prefabs/Items/Equipment/Radios/Radio_ANPRC77.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AAFD205EE}" {
     m_eItemType RADIO_BACKPACK
     m_iSupplyCost 50
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AAFD205ED}" {
   m_sEntityPrefab "{5C5C6EE05EE2FF1A}Prefabs/Items/Equipment/Backpacks/Backpack_ALICE_Medium_assembled.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AAFD205E2}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AAFD205E3}" {
   m_sEntityPrefab "{4805E67E2AE30F8D}Prefabs/Items/Equipment/Backpacks/Backpack_Medical_M5.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AAFD27E35}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AAFD27E37}" {
   m_sEntityPrefab "{95D4766BBE46F23D}Prefabs/Items/Equipment/Backpacks/Backpack_IIFS_FieldPack.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AAFD27E30}" {
     m_eItemType BACKPACK
     m_iSupplyCost 0
    }
   }
  }
 }
}