SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Eyewear (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710AC74BE392}" {
   m_sEntityPrefab "{059BBD768632F474}Prefabs/Characters/Eyewear/npp_kondor/Eyewear_npp_kondor_smoke.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AC74BE398}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AC74BE385}" {
   m_sEntityPrefab "{11E7A27E17A9198C}Prefabs/Characters/Eyewear/npp_kondor/Eyewear_npp_kondor_olive_smoke.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AC74BF74D}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AC74BF74E}" {
   m_sEntityPrefab "{27A692844476B992}Prefabs/Characters/Eyewear/npp_kondor/Eyewear_npp_kondor_tan_smoke.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AC74A0BCA}" {
     m_eItemType FACEWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}