SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Tshirts (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710A0CB919C1}" {
   m_sEntityPrefab "{29E0D0D114B01115}Prefabs/Characters/Uniforms/Shirt_TShirt_ION/Shirt_TShirt_ION_Tan.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A0CB919DE}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A0CB919D9}" {
   m_sEntityPrefab "{198347D84D5BEDE7}Prefabs/Characters/Uniforms/Shirt_TShirt/Shirt_TShirt_CoyoteBrown.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A0CBAF948}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A0CBAF94A}" {
   m_sEntityPrefab "{30B487CBDE0059E9}Prefabs/Characters/Uniforms/Shirt_TShirt/Shirt_TShirt_Gray.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A0CBAF945}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A0CBAF944}" {
   m_sEntityPrefab "{4A2E7B5F181F06CE}Prefabs/Characters/Uniforms/Shirt_Velocity/Shirt_Velocity_CoyoteBrown.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A0CBA4E2C}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A0CBA4E2F}" {
   m_sEntityPrefab "{4E2FDAB4DDA47B54}Prefabs/Characters/Uniforms/Shirt_Velocity/Shirt_Velocity_Gray.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A0CBA39BE}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710A0CBA39BF}" {
   m_sEntityPrefab "{0DBF54F1A148C42E}Prefabs/Characters/Uniforms/Shirt_Velocity/Shirt_Velocity_MC.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710A0CBB9E21}" {
     m_eItemType TORSO
     m_iSupplyCost 0
    }
   }
  }
 }
}