SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Boonies (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710ADC92CC7E}" {
   m_sEntityPrefab "{157C41164D734D2C}Prefabs/Characters/HeadGear/Hats/Hat_Boonie_Reforger/Hat_Boonie_Reforger_OD.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADC92CC75}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ADC92CC77}" {
   m_sEntityPrefab "{770057A7356E883B}Prefabs/Characters/HeadGear/Hats/Hat_Boonie_Reforger/Hat_Boonie_Reforger_M81_Woodland.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADC92CC70}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ADC92CC71}" {
   m_sEntityPrefab "{77CFDEF3D4198A18}Prefabs/Characters/HeadGear/Hats/Hat_Boonie_Reforger/Hat_Boonie_Reforger_TigerStripe.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADC92CC72}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ADC92CC73}" {
   m_sEntityPrefab "{0D2636B622400595}Prefabs/Characters/HeadGear/Hats/Hat_Boonie_Reforger/Hat_Boonie_Reforger_VZ95.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADC935A5B}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ADC935A25}" {
   m_sEntityPrefab "{BCAED055762E7ADC}Prefabs/Characters/HeadGear/Hats/Hat_Boonie/Hat_Boonie_Black.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADC935A26}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ADC935A27}" {
   m_sEntityPrefab "{76E0893A3FA03C26}Prefabs/Characters/HeadGear/Hats/Hat_Boonie/Hat_Boonie_CoyoteBrown.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADC9341AD}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ADC9341AA}" {
   m_sEntityPrefab "{B326AE4B5D0294B8}Prefabs/Characters/HeadGear/Hats/Hat_Boonie/Hat_Boonie_Desert.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADC9341AB}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ADC939BFF}" {
   m_sEntityPrefab "{BA4627D179A65D75}Prefabs/Characters/HeadGear/Hats/Hat_Boonie/Hat_Boonie_Green.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADC939BF6}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ADC939BF7}" {
   m_sEntityPrefab "{8142DCBA6FCD8CF1}Prefabs/Characters/HeadGear/Hats/Hat_Boonie/Hat_Boonie_MC.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADC939BF4}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ADC939BF5}" {
   m_sEntityPrefab "{A41AAC1ADB161E04}Prefabs/Characters/HeadGear/Hats/Hat_Boonie/Hat_Boonie_MC_Arid.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADC93E7E6}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ADC93E7F9}" {
   m_sEntityPrefab "{567582198EF8456E}Prefabs/Characters/HeadGear/Hats/Hat_Boonie/Hat_Boonie_MC_Black.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADC93E7F8}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710ADC93C236}" {
   m_sEntityPrefab "{52622893F3E4DB26}Prefabs/Characters/HeadGear/Hats/Hat_Boonie/Hat_Boonie_OD.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710ADC93C235}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}