SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Clothing - Headgear (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710AFD99D0D4}" {
   m_sEntityPrefab "{F545C1BE7C99954A}Prefabs/Characters/HeadGear/Hat_Patrol_US_01/Hat_Patrol_US_01.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AFD99D0D2}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AFD99D0AC}" {
   m_sEntityPrefab "{9911F55EC05D1A64}Prefabs/Characters/HeadGear/Hat_Patrol_US_01/Hat_Patrol_US_02.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AFD99D0AF}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710AFD99D0AE}" {
   m_sEntityPrefab "{56915D05E3190762}Prefabs/Characters/HeadGear/Hat_Patrol_US_01/Hat_Patrol_US_01_TigerStripe.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710AFD99D0A9}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 0
    }
   }
  }
 }
}