SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Helicopters (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB58FB6C3A2}" {
   m_sEntityPrefab "{FA8556A46D3A6FDA}Prefabs/Weapons/AircraftWeapons/RocketPods/Pod_UB1657.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB58FB6C398}" {
     m_eItemType HELICOPTER
     m_eItemMode PYLON
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB58FB6C39B}" {
   m_sEntityPrefab "{38FB8EE4CCACB7EC}Prefabs/Weapons/AircraftWeapons/RocketPods/Pod_UB1657_Loaded_HEDP_S5KO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB58FB6377D}" {
     m_eItemType HELICOPTER
     m_eItemMode PYLON
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB58FB6377B}" {
   m_sEntityPrefab "{0D920C0DF31DC4D4}Prefabs/Weapons/AircraftWeapons/RocketPods/Pod_UB1657_Loaded_FRAG_S5MO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB58FB63778}" {
     m_eItemType HELICOPTER
     m_eItemMode PYLON
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB58FB63779}" {
   m_sEntityPrefab "{EF17BED6DCEE4DE4}Prefabs/Weapons/Ammo/Ammo_Rocket_S5_FRAG_S5MO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB58FB67490}" {
     m_eItemType HELICOPTER
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB58FB6749E}" {
   m_sEntityPrefab "{EE65544BA845C458}Prefabs/Weapons/Ammo/Ammo_Rocket_S5_HEDP_S5KO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB58FB6749D}" {
     m_eItemType HELICOPTER
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
 }
}