SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Vehicles (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB5AEA0BD04}" {
   m_sEntityPrefab "{8BD7CB61BD6AFD69}Prefabs/Weapons/Magazines/Box_23x152_ZU23_100rnd_2HEIT_1APIT.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5AEA0BD01}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 20
    }
   }
  }
 }
}