SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Grenade Launchers (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB58AF3BAE3}" {
   m_sEntityPrefab "{262F0D09C4130826}Prefabs/Weapons/Ammo/Ammo_Grenade_HE_VOG25.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB58AF3BAE9}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB58AF3BAEB}" {
   m_sEntityPrefab "{906F07BD0366E08F}Prefabs/Weapons/Ammo/Ammo_Flare_40mm_VG40OP_White.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB58AF3BAEC}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
 }
}