SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Launchers (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB5B278BC31}" {
   m_sEntityPrefab "{4A3B196E4EA820E9}Prefabs/Weapons/Ammo/RPG/RHS_AmmoRocket_OG7V.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5B278BC3B}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 20
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5B278BC38}" {
   m_sEntityPrefab "{1E23C81AB8A24F49}Prefabs/Weapons/Ammo/RPG/RHS_AmmoRocket_PG7VM.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5B278BC27}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 40
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5B278BC26}" {
   m_sEntityPrefab "{FBBF84E3B447D822}Prefabs/Weapons/Ammo/RPG/RHS_AmmoRocket_PG7VL.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5B26759D4}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 40
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5B26759D6}" {
   m_sEntityPrefab "{86A7681BD1D4E4BB}Prefabs/Weapons/Ammo/RPG/RHS_AmmoRocket_PG7VR.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5B26759D1}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 40
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5B26759D0}" {
   m_sEntityPrefab "{12AFA740BE9ED3CD}Prefabs/Weapons/Ammo/RPG/RHS_AmmoRocket_TBG7V.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5B267332F}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 80
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5B267332C}" {
   m_sEntityPrefab "{9535D6E39DCA78FB}Prefabs/Weapons/Ammo/RPG/RHS_AmmoRocket_TBG7VL.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5B267332D}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 80
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5B2673322}" {
   m_sEntityPrefab "{D3CCDE5C34549F1A}Prefabs/Weapons/Magazines/GM94/Magazine_43x30mm_GM94_4rnd_VGM93900.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5B267AA8A}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5B267AA8B}" {
   m_sEntityPrefab "{FDACA6E5AEC36BD0}Prefabs/Weapons/Magazines/GM94/Magazine_43x30mm_GM94_4rnd_VGM93100.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5B267AA88}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
 }
}