SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Vehicles (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB5AC6A404B}" {
   m_sEntityPrefab "{988E7C4F812130FA}Prefabs/Weapons/Magazines/2A42/Box_30mm_2A42_APFSDS_250rnd.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5AC6A4041}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5AC6A4043}" {
   m_sEntityPrefab "{479FDB5EDD601394}Prefabs/Weapons/Magazines/2A42/Box_30mm_2A42_HE_250rnd.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5AC6A4044}" {
     m_eItemType MACHINE_GUN
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5AC6A4045}" {
   m_sEntityPrefab "{EB33480A62A31B04}Prefabs/Weapons/Magazines/2A82/Box_125mm_2A82_APFSDST_20rnd.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5AC6A4046}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5AC6A4047}" {
   m_sEntityPrefab "{C502CADC032E147E}Prefabs/Weapons/Magazines/2A82/Box_125mm_2A82_HEFragFS_19rnd.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5AC6AB067}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5AC6AB079}" {
   m_sEntityPrefab "{A2B376B9B13737A0}Prefabs/Weapons/Magazines/9M113/Box_Rockets_9M113_4.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5AC6A9845}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5AC6A9846}" {
   m_sEntityPrefab "{F3B9EB4DD5006E54}Prefabs/Weapons/Magazines/AGS30/Box_30mm_AGS30_150.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5AC6A9847}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
 }
}