SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Ammunition - Rifles (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB5BF074EC6}" {
   m_sEntityPrefab "{BBB50A815A2F916B}Prefabs/Weapons/Magazines/Magazine_545x39_AK_30rnd_Ball.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5BF074EBC}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5BF074EBE}" {
   m_sEntityPrefab "{0A84AA5A3884176F}Prefabs/Weapons/Magazines/Magazine_545x39_AK_30rnd_Last_5Tracer.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5BF074EB9}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5BF074EBB}" {
   m_sEntityPrefab "{E5912E45754CD421}Prefabs/Weapons/Magazines/Magazine_545x39_AK_30rnd_Tracer.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5BF074EBA}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
 }
}