SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Optics (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB5F6988226}" {
   m_sEntityPrefab "{C850A33226B8F9C1}Prefabs/Weapons/Attachments/Optics/Scopes/Optic_PSO1/Optic_PSO1.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F698821C}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F698821F}" {
   m_sEntityPrefab "{ACDF49FACD0701A8}Prefabs/Weapons/Attachments/Optics/Scopes/Optic_1P29/Optic_1P29.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F6988210}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F6988211}" {
   m_sEntityPrefab "{E5E9DBBF3BFB88C6}Prefabs/Weapons/Attachments/Optics/Optic_PGO7/Optic_PGO7V3.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F6988212}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}