SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Suppressors (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB5E0FB08A8}" {
   m_sEntityPrefab "{11D838FCDDF91842}Prefabs/Weapons/Attachments/Muzzle/545x39/Suppressor_PBS4_base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5E0FB0895}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}