SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Muzzle (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB5F087F827}" {
   m_sEntityPrefab "{68FA089585881190}Prefabs/Weapons/Attachments/Muzzle/545x39/MuzzleBrake_AK74_base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F087F82D}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F087F82E}" {
   m_sEntityPrefab "{AD6470E1636E441F}Prefabs/Weapons/Attachments/Muzzle/545x39/MuzzleBrake_AKS74u_base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F086393D}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}