SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Muzzle (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB5F4C155D8}" {
   m_sEntityPrefab "{9E6A9A314E7D2539}Prefabs/Weapons/Attachments/Muzzle/762x39/MuzzleBrake_AKM.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F4C155DE}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F4C155D1}" {
   m_sEntityPrefab "{E2E4A5A05389DCA5}Prefabs/Weapons/Attachments/Muzzle/545x39/MuzzleBrake_AK12.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F4C15583}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F4C15581}" {
   m_sEntityPrefab "{2B9219ED7E49B0DC}Prefabs/Weapons/Attachments/Muzzle/762x39/MuzzleBrake_DTK1.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F4C15586}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F4C15587}" {
   m_sEntityPrefab "{46EF3F778F2ACE76}Prefabs/Weapons/Attachments/Muzzle/545x39/MuzzleBrake_DTK1_545.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F4C11F70}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F4C11F73}" {
   m_sEntityPrefab "{47C62D0DC28D3FF2}Prefabs/Weapons/Attachments/Muzzle/762x39/MuzzleBrake_DTK2.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F4C11F72}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F4C11F4D}" {
   m_sEntityPrefab "{F4387D9CD088FDEE}Prefabs/Weapons/Attachments/Muzzle/545x39/MuzzleBrake_DTK2_545.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F4C2F1D0}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F4C2F1D2}" {
   m_sEntityPrefab "{27EEF4C2AFD8176E}Prefabs/Weapons/Attachments/Muzzle/762x54r/MuzzleBrake_PKP.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F4C2F1D3}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F4C2F1D4}" {
   m_sEntityPrefab "{59964C628478D2AA}Prefabs/Weapons/Attachments/Muzzle/9x19/MuzzleBreak_PP19.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F4C2B49C}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F4C2B492}" {
   m_sEntityPrefab "{59A41C7D3A510DF6}Prefabs/Weapons/Attachments/Muzzle/762x51/FlashHider_SvCh_base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F4C2B493}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}