SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Other (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB5FF81A913}" {
   m_sEntityPrefab "{D901305DD97960AD}Prefabs/Weapons/Attachments/Misc/AkGpButtPad/akGPbutt.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5FF81A91D}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}