SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Grips (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB5C5B314A1}" {
   m_sEntityPrefab "{8B408A3D9367CB43}Prefabs/Weapons/Attachments/Grips/Grip_Zenit_RK_Vertical/RHS_RK0_base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5C5B314AF}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5C5B314A9}" {
   m_sEntityPrefab "{74C04C2D52EE4276}Prefabs/Weapons/Attachments/Grips/Grip_Zenit_RK_Vertical/RHS_RK1.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5C5B314AA}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5C5B31494}" {
   m_sEntityPrefab "{A1E44FF2462F2AB7}Prefabs/Weapons/Attachments/Grips/Grip_Zenit_RK_Vertical/RHS_RK1_B25U.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5C5B31F3A}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5C5B31F38}" {
   m_sEntityPrefab "{189478CDEE2ACD58}Prefabs/Weapons/Attachments/Grips/Grip_Zenit_RK_Vertical/RHS_RK2.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5C5B29687}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5C5B29686}" {
   m_sEntityPrefab "{49F469152782CB41}Prefabs/Weapons/Attachments/Grips/Grip_Zenit_RK_Vertical/RHS_RK6.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5C5B29681}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}