SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Tactical (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB5EF2479BC}" {
   m_sEntityPrefab "{FAB4CF231369431F}Prefabs/Weapons/Attachments/TacticalDevices/NcSTAR/Laser_NcSTAR_base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5EF247986}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}