SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Grips (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB5C72419AF}" {
   m_sEntityPrefab "{B474F5CF43FCBACC}Prefabs/Weapons/Attachments/Foregrips/RK_Foregrips/Foregrip_RK0.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5C72419B5}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5C72419B6}" {
   m_sEntityPrefab "{18E29C6FBEFD764D}Prefabs/Weapons/Attachments/Foregrips/RK_Foregrips/Foregrip_RK1_B25U.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5C72419B1}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5C72419B0}" {
   m_sEntityPrefab "{3DBC8DD6F3DDA289}Prefabs/Weapons/Attachments/Foregrips/RK_Foregrips/Foregrip_RK2.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5C72419B3}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5C724B8A3}" {
   m_sEntityPrefab "{E514E4178A54BCD5}Prefabs/Weapons/Attachments/Foregrips/RK_Foregrips/Foregrip_RK4.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5C724B8A2}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5C724B8AD}" {
   m_sEntityPrefab "{6CDC9C0E3A75A490}Prefabs/Weapons/Attachments/Foregrips/RK_Foregrips/Foregrip_RK6.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5C724B8AC}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}