SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapon Attachments - Muzzle (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB5F2C82D22}" {
   m_sEntityPrefab "{BAC59BF0DF432D43}Prefabs/Weapons/Attachments/Muzzle/RHS_PGS64.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F2C82D24}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F2C82D2A}" {
   m_sEntityPrefab "{07AF951403CBAB0A}Prefabs/Weapons/Attachments/Muzzle/AK103_muzzle/RHS_AK103_muzzle.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F2C82D2B}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F2C82D28}" {
   m_sEntityPrefab "{07BCACE1DE243320}Prefabs/Weapons/Attachments/Muzzle/AK105_muzzle/RHS_AK105_muzzle.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F2C82D29}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F2C82D2E}" {
   m_sEntityPrefab "{0147EC1780C80AEF}Prefabs/Weapons/Attachments/Muzzle/AK200_muzzle/RHS_AK200_muzzle.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F2C82D2F}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F2C8305E}" {
   m_sEntityPrefab "{91D5624C80CD29AB}Prefabs/Weapons/Attachments/Muzzle/Zenit_DTK2_Muzzle/RHS_AK74M_Zenit_DTK1_Muzzle_Base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F2C8305C}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F2C86A37}" {
   m_sEntityPrefab "{A35F86E4B492AE13}Prefabs/Weapons/Attachments/Muzzle/Zenit_DTK2_Muzzle/RHS_AK74M_Zenit_DTK2_Muzzle_Base.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F2C86A08}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB5F2C86A09}" {
   m_sEntityPrefab "{DEBB01A41488DFF8}Prefabs/Weapons/Attachments/Muzzle/RHS_6P20_0_20.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB5F2C88169}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}