SCR_GroupRolePresetConfig {
 m_eGroupRole MAIN_BATTLE_TANK
 m_sGroupFlagName "mbt"
 m_iGroupSize 3
 m_eRequiredRank CAPTAIN
 m_iMaxGroups 3
 m_sGroupRoleName "#WCS-GroupRole-MBT"
 m_aLoadoutResources {
  "{8DB1C1F194CBACF8}Prefabs/Characters/Campaign/Final/OPFOR/USSR_Army/Regular/Campaign_USSR_Player_Crew.et"
  "{8DB1C1F194CBACF8}Prefabs/Characters/Campaign/Final/OPFOR/USSR_Army/Regular/Campaign_USSR_Player_Crew.et"
  "{8DB1C1F194CBACF8}Prefabs/Characters/Campaign/Final/OPFOR/USSR_Army/Regular/Campaign_USSR_Player_Crew.et"
 }
}