SCR_GroupRolePresetConfig {
 m_eGroupRole INFANTRY_FIGHTING_VEHICLE
 m_sGroupFlagName "ifv"
 m_iGroupSize 3
 m_eRequiredRank CAPTAIN
 m_iMaxGroups 4
 m_sGroupRoleName "#WCS-GroupRole-IFV"
 m_aLoadoutResources {
  "{8DB1C1F194CBACF8}Prefabs/Characters/Campaign/Final/OPFOR/USSR_Army/Regular/Campaign_USSR_Player_Crew.et"
  "{8DB1C1F194CBACF8}Prefabs/Characters/Campaign/Final/OPFOR/USSR_Army/Regular/Campaign_USSR_Player_Crew.et"
  "{8DB1C1F194CBACF8}Prefabs/Characters/Campaign/Final/OPFOR/USSR_Army/Regular/Campaign_USSR_Player_Crew.et"
 }
}