SCR_GroupRolePresetConfig {
 m_eGroupRole ATTACK_HELICOPTER
 m_sGroupFlagName "attackhelicopter"
 m_iGroupSize 2
 m_eRequiredRank CAPTAIN
 m_iMaxGroups 2
 m_sGroupRoleName "#WCS-GroupRole-AttackHelicopter"
 m_aLoadoutResources {
  "{DB239B6C4AC64BCE}Prefabs/Characters/Campaign/Final/OPFOR/USSR_Army/Regular/Campaign_USSR_Player_HeliPilot.et"
  "{7A5EEFF20EA663E6}Prefabs/Characters/Campaign/Final/OPFOR/USSR_Army/Regular/Campaign_USSR_Player_HeliCrew.et"
 }
}