SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Explosives - Mortars (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7DB66B89FCBA}" {
   m_sEntityPrefab "{B41607EAB58A4252}Prefabs/Items/Equipment/BallisticTable/BallisticTable_USSR.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB66B89FCBF}" {
     m_eItemType MORTARS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB66B89FCA2}" {
   m_sEntityPrefab "{7DF4266A58BF088F}Prefabs/Props/Military/AmmoBoxes/AmmoBox_82mm_mortar_3rnd.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB66B89FCA3}" {
     m_eItemType MORTARS
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 5
     m_aArsenalAlternativeCostData {
      SCR_ArsenalAlternativeCostSellAmountData "{697D7DB66B89FCA4}" {
       m_eAlternativeCostType DEFAULT
       m_iSupplyCost 5
       m_iSupplyRefundAmount 5
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB66B89FCA5}" {
   m_sEntityPrefab "{98EC9C526AFBA282}Prefabs/Weapons/Ammo/Ammo_Shell_82mm_HE_O832DU.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB66B89FCA6}" {
     m_eItemType MORTARS
     m_eItemMode AMMUNITION
     m_iSupplyCost 20
    }
    SCR_EntityCatalogSupportStationResupplyData "{697D7DB66B89FCA7}" {
     m_eResupplyType MORTAR_SHELL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB66B89FCA8}" {
   m_sEntityPrefab "{C8A906FB198D1A33}Prefabs/Weapons/Ammo/Ammo_Shell_82mm_Illum_S832S.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB66B89842D}" {
     m_eItemType MORTARS
     m_eItemMode AMMUNITION
     m_iSupplyCost 5
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7DB66B89842F}" {
   m_sEntityPrefab "{A544A2C131DE2C64}Prefabs/Weapons/Ammo/Ammo_Shell_82mm_Smoke_D832DU.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7DB66B89842E}" {
     m_eItemType MORTARS
     m_eItemMode AMMUNITION
     m_iSupplyCost 5
    }
   }
  }
 }
}