SCR_MissionHeaderCampaign {
 World "{DA23D95F5CABDAF7}Worlds/BelleauWood/BelleauWoodAAS/BelleauWood.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Podval #1 BelleauWood AAS"
 m_sAuthor "SILENCE & Podval"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{2756229DA9DAD415}UI/Textures/MissionLoadingScreens/Reforger_HQCArt_Everon_UI.edds"
 m_sLoadingScreen "{2756229DA9DAD415}UI/Textures/MissionLoadingScreens/Reforger_HQCArt_Everon_UI.edds"
 m_sPreviewImage "{2756229DA9DAD415}UI/Textures/MissionLoadingScreens/Reforger_HQCArt_Everon_UI.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
}