SCR_MissionHeaderCampaign {
 World "{C84C84DF6FAA88E5}Worlds/BelleauWood/BelleauWoodDAAS/BelleauWoodDAAS.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "BelleauWood DAAS"
 m_sAuthor "Podval & WCS"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_bRandomStartingDaytime 1
 m_bRandomStartingWeather 1
}