SCR_MissionHeaderCampaign {
 World "{43CA30D66155A438}Worlds/Enden/Northern Everon/Northern_Everon_0.1.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Podval Northern Everon"
 m_sAuthor "PODVAL"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{62897631F4A6C7F3}UI/Textures/MissionLoadingScreens/Reforger_ConflictArt_UI.edds"
 m_sLoadingScreen "{62897631F4A6C7F3}UI/Textures/MissionLoadingScreens/Reforger_ConflictArt_UI.edds"
 m_sPreviewImage "{818C80AD02C1007B}UI/Textures/MissionLoadingScreens/Reforger_ConflictIcon_UI.edds"
 m_sGameMode "#AR-Scenario_GameMode_Campaign"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags SpawnVehicles
 m_fNightTimeAcceleration 8
 m_aFactionLimits {
  SCR_FactionLimit "{69451B9A802021CA}" {
   m_sFactionKey "FIA"
   m_iFactionLimit 0
  }
 }
}