SCR_MissionHeaderCampaign {
 World "{4341AD1A824CE505}Worlds/Chernarus/Chernarus_AAS/Chernarus_AAS.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Chernarus AAS"
 m_sAuthor "Podval & WCS"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{7489B79DB25DB5D4}UI/Textures/MissionThumbnails/CAH_Castle_Thumbnail_UI.edds"
 m_sLoadingScreen "{8E135C7AA80F6861}UI/Textures/MissionLoadingScreens/CO_Arland_05.edds"
 m_sPreviewImage "{EC0B73DC1409A326}UI/Textures/MissionLoadingScreens/CAH_Castle_UI.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags SpawnVehicles
 m_eDefaultGameFlags SpawnVehicles
}