SCR_MissionHeaderCampaign {
 World "{87B4CCB5C2202F72}Worlds/Chernarus/Chernarus_Conflict/Chernarus_Conflict_Layers/Chernarus_Conflict.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Chernarus Conflict"
 m_sAuthor "Podval"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{E188A17B88D252DB}UI/Textures/MissionLoadingScreens/LoadingScreenSurvival.edds"
 m_sLoadingScreen "{A9791E5C9BCD80BD}UI/Textures/MissionLoadingScreens/CAH_Forest_UI.edds"
 m_sPreviewImage "{3011E6CC5E7D976A}UI/Textures/MissionLoadingScreens/placeholder_6_UI.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags SpawnVehicles
 m_eDefaultGameFlags SpawnVehicles
}