SCR_MissionHeaderCampaign {
 World "{409C4D45EBD5BCA7}Worlds/Everon/Everon_Conflict/Everon_Conflict.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Podval #1 Everon Conflict"
 m_sAuthor "SILENCE & Podval"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sGameMode "#AR-Scenario_GameMode_Campaign"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
}