SCR_MissionHeaderCampaign {
 World "{8CA0689865BB4789}Worlds/Kolguyev/Kolguev_AAS_South/Kolguev_AAS_South.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Kolguev AAS South"
 m_sAuthor "PODVAL"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags SpawnVehicles
 m_eDefaultGameFlags SpawnVehicles
}