SCR_MissionHeaderCampaign {
 World "{162084238505179F}Worlds/Luna/LunaAAS.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Luna AAS"
 m_sAuthor "Podval"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{94B5BCA6E3C20820}Images/4.edds"
 m_sLoadingScreen "{94B5BCA6E3C20820}Images/4.edds"
 m_sPreviewImage "{94B5BCA6E3C20820}Images/4.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags SpawnVehicles
 m_eDefaultGameFlags SpawnVehicles
}