SCR_MissionHeaderCampaign {
 World "{FEC3063DF47790CA}Worlds/Rostov/RostovConflict/RostovConflict.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Podval Rostov"
 m_sAuthor "PODVAL"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
}