SCR_MissionHeaderCampaign {
 World "{9A914336E71F0FA4}Worlds/Ruha/RuhaAAS.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Ruha AAS"
 m_sAuthor "PODVAL"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{5AFBCE5DE231F9E8}UI/Textures/MissionThumbnails/ruha_default.edds"
 m_sLoadingScreen "{55DA4523CEB4B0C6}UI/Textures/MissionThumbnails/lr_ruha2.edds"
 m_sPreviewImage "{55DA4523CEB4B0C6}UI/Textures/MissionThumbnails/lr_ruha2.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags SpawnVehicles
 m_eDefaultGameFlags SpawnVehicles
}