SCR_MissionHeaderCampaign {
 World "{373A1FE2A4831AAA}Worlds/Serhiivka/SerhiivkaAAS/SerhiivkaAAS.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Serhiivka  AAS"
 m_sAuthor "Podval & WCS"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{B1C471A4D3E9D676}UI/Textures/MissionLoadingScreens/WCS_Serhiivka_Conflict.edds"
 m_sLoadingScreen "{B1C471A4D3E9D676}UI/Textures/MissionLoadingScreens/WCS_Serhiivka_Conflict.edds"
 m_sPreviewImage "{F6EDB3E90A1A964B}UI/Textures/MissionLoadingScreens/WCS_Serhiivka.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
}