SCR_MissionHeaderCampaign {
 World "{71D5076A79A82CA4}Worlds/SILENCE_Island/SILENCE_Island.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "SILENCE's Island"
 m_sAuthor "PODVAL"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{4327F9259AFAFFB2}20231107230858_1.edds"
 m_sLoadingScreen "{4327F9259AFAFFB2}20231107230858_1.edds"
 m_sPreviewImage "{4327F9259AFAFFB2}20231107230858_1.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags SpawnVehicles
 m_eDefaultGameFlags SpawnVehicles
}