SCR_MissionHeaderCampaign {
 World "{5900924B0CDB2CE2}Worlds/Takistan/Takistan_AAS/Takistan_AAS.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Takistan AAS"
 m_sAuthor "Podval"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sLoadingScreen "{B7F6E6C33EFD787E}UI/Textures/MissionLoadingScreens/CO_Eden.edds"
 m_sPreviewImage "{3011E6CC5E7D976A}UI/Textures/MissionLoadingScreens/placeholder_6_UI.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags SpawnVehicles
 m_eDefaultGameFlags SpawnVehicles
}