SCR_MissionHeaderCampaign {
 World "{1F79BC3C8610EA88}Worlds/Worthy_Islands/Worthy_Islands_Conflict.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Worthy Islands Conflict"
 m_sAuthor "Podval"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sIcon "{83A3BF515EE215A8}thumbnail.edds"
 m_sLoadingScreen "{83A3BF515EE215A8}thumbnail.edds"
 m_sPreviewImage "{83A3BF515EE215A8}thumbnail.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags SpawnVehicles
 m_eDefaultGameFlags SpawnVehicles
}