SCR_MissionHeaderCampaign {
 World "{BA4259A65B02AED4}Worlds/Zargabad/Zargabad_AAS/Zargabad_AAS.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Podval Zargabad AAS"
 m_sAuthor "PODVAL"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
}