SCR_MissionHeaderCampaign {
 World "{3A35BA03CD5109CB}Worlds/Zargabad/Zargabad_AAS1/Zargabad.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "Zargabad AAS #1"
 m_sAuthor "Podval"
 m_sDescription "#AR-Campaign_GamemodeDesc"
 m_sDetails "#AR-Campaign_Hint_Signal_Text"
 m_sLoadingScreen "{B7F6E6C33EFD787E}UI/Textures/MissionLoadingScreens/CO_Eden.edds"
 m_sPreviewImage "{3011E6CC5E7D976A}UI/Textures/MissionLoadingScreens/placeholder_6_UI.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
}