SCR_MissionHeaderCampaign {
 World "{7F8D4511A6763F93}Worlds/Zarichne/Name/Zarichne_v0.1.ent"
 m_sName "PODVAL Zarichne"
 m_sAuthor "PODVAL"
 m_sDescription "<Insert world description>"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 64
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
}