SCR_GroupRolePresetConfig {
 m_eGroupRole MAIN_BATTLE_TANK
 m_sGroupFlagName "mbt"
 m_iGroupSize 3
 m_eRequiredRank CAPTAIN
 m_iMaxGroups 3
 m_sGroupRoleName "#WCS-GroupRole-MBT"
 m_aLoadoutResources {
  "{7EC9243A1A11A335}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Regular/Campaign_US_Player_Crew.et"
  "{7EC9243A1A11A335}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Regular/Campaign_US_Player_Crew.et"
  "{7EC9243A1A11A335}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Regular/Campaign_US_Player_Crew.et"
 }
}