SCR_GroupRolePresetConfig {
 m_eGroupRole ATTACK_HELICOPTER
 m_sGroupFlagName "attack-helicopter"
 m_iGroupSize 2
 m_eRequiredRank CAPTAIN
 m_iMaxGroups 2
 m_sGroupRoleName "#WCS-GroupRole-AttackHelicopter"
 m_aLoadoutResources {
  "{8A9CB3744F3B947C}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Regular/Campaign_US_Player_HeliPilot.et"
  "{8652BD1E0C9725D7}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Regular/Campaign_US_Player_HeliCrew.et"
 }
}