SCR_GroupRolePresetConfig {
 m_eGroupRole INFANTRY_FIGHTING_VEHICLE
 m_sGroupFlagName "ifv"
 m_iGroupSize 3
 m_eRequiredRank CAPTAIN
 m_iMaxGroups 4
 m_sGroupRoleName "#WCS-GroupRole-IFV"
 m_aLoadoutResources {
  "{7EC9243A1A11A335}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Regular/Campaign_US_Player_Crew.et"
  "{7EC9243A1A11A335}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Regular/Campaign_US_Player_Crew.et"
  "{7EC9243A1A11A335}Prefabs/Characters/Campaign/Final/BLUFOR/US_army/Regular/Campaign_US_Player_Crew.et"
 }
}