SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Launchers (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697B6CB8E050A5F2}" {
   m_sEntityPrefab "{3DF204EEE0534EF2}Prefabs/Weapons/Launchers/FIM92_Stinger/Launcher_FIM92_Stinger.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8E050A5C8}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 100
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8E050A5C5}" {
   m_sEntityPrefab "{246737687711A367}Prefabs/Weapons/Launchers/FGM148_Javelin/Launcher_FGM148_Javelin.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8E050A5C4}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 200
     m_eRequiredRank COLONEL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8E050A5C7}" {
   m_sEntityPrefab "{9C5C20FB0E01E64F}Prefabs/Weapons/Launchers/M72/Launcher_M72A3.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8E050A5C6}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 50
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8E050A5C1}" {
   m_sEntityPrefab "{DA376E83952F1DFD}Prefabs/Weapons/Launchers/M2CG/Launcher_M2CG.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8E0576F14}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 40
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8E0576F16}" {
   m_sEntityPrefab "{DB53366D8C521124}Prefabs/Weapons/Launchers/MK153/Launcher_MK153mod2_NoMBS.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8E0570FD9}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 40
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8E0570FD8}" {
   m_sEntityPrefab "{35022055DCDDE98B}Prefabs/Weapons/Launchers/MK153/Launcher_MK153mod2.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8E0570FC7}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 40
    }
   }
  }
 }
}