SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Snipers (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7109674AA17D}" {
   m_sEntityPrefab "{9A2AA760B16BCDBE}Prefabs/Weapons/Rifles/M40/Rifle_M40A5.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109674AA164}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7109674AA167}" {
   m_sEntityPrefab "{8909A91CFF369BB3}Prefabs/Weapons/Rifles/M40/Rifle_M40A5_Optic.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109674AC0D0}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
 }
}