SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Machine Guns (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710974069D00}" {
   m_sEntityPrefab "{D2B48DEBEF38D7D7}Prefabs/Weapons/MachineGuns/M249/MG_M249.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710974069D0A}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710974069D37}" {
   m_sEntityPrefab "{D182DCDD72BF7E34}Prefabs/Weapons/MachineGuns/M60/MG_M60.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710974069D36}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}