SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Launchers (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697B6CB8FED5B195}" {
   m_sEntityPrefab "{DB53366D8C521124}Prefabs/Weapons/Launchers/MK153/Launcher_MK153mod2_NoMBS.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8FED5B193}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8FED5B16D}" {
   m_sEntityPrefab "{35022055DCDDE98B}Prefabs/Weapons/Launchers/MK153/Launcher_MK153mod2.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8FED5B16C}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8FED5B16F}" {
   m_sEntityPrefab "{0228B8EFBA99AC1D}Prefabs/Weapons/Misc/SpectrumDevice/Device_SpectrumDevice_base.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8FED5B16E}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}