SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Carbine Rifles (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697B6CB8F1D10D94}" {
   m_sEntityPrefab "{D6516486D998AA0B}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine_weaver.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8F1D10D9E}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8F1D10D9C}" {
   m_sEntityPrefab "{6AB4AD4ADACB008B}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_EOT.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8F1D10D9D}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8F1D10D9B}" {
   m_sEntityPrefab "{139B1F6E64109536}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_EOT_pmag.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8F1D10D98}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8F1D139AE}" {
   m_sEntityPrefab "{4910F1F60DEE5DC9}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_rmr.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8F1D139AF}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8F1D139B0}" {
   m_sEntityPrefab "{19A852B58F40E4EB}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_rmr_warden.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8F1D139B1}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8F1D1D046}" {
   m_sEntityPrefab "{C20882A2C3211738}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_T1_sf.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8F1D1D045}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8F1D1D044}" {
   m_sEntityPrefab "{B5CF61A72D0BA15D}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_T1_warden.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8F1D1D043}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8F1D1FEF4}" {
   m_sEntityPrefab "{CBE985125ACE93DA}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_T1_pmag.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8F1D1FEF5}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8F1D1E403}" {
   m_sEntityPrefab "{C0F632AEF921F4C8}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_T1_pmag_warden.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8F1D1E400}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}