SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Machine Guns (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710978D5D9DF}" {
   m_sEntityPrefab "{D2B48DEBEF38D7D7}Prefabs/Weapons/MachineGuns/M249/MG_M249.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710978D5D9D9}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710978D5D9D7}" {
   m_sEntityPrefab "{D688A947EBC71A04}Prefabs/Weapons/MachineGuns/M249/MG_M249_PIP.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710978D5D9D5}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710978D5D9D4}" {
   m_sEntityPrefab "{D182DCDD72BF7E34}Prefabs/Weapons/MachineGuns/M60/MG_M60.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710978D5D9D3}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710978D5C40F}" {
   m_sEntityPrefab "{49746016A5758D0C}Prefabs/Weapons/MachineGuns/M60/MG_M60E4_EXPS3.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710978D5C40D}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710978D659B3}" {
   m_sEntityPrefab "{E9059598E8595760}Prefabs/Weapons/MachineGuns/M60/MG_M60E4_TA648MDO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710978D659B2}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710978D6598D}" {
   m_sEntityPrefab "{A87B0A22462E20B1}Prefabs/Weapons/MachineGuns/M240/MG_M240.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710978D6598C}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710978D65368}" {
   m_sEntityPrefab "{441C6358A2167AE3}Prefabs/Weapons/MachineGuns/M240/MG_M240_MDO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710978D6536B}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710978D6536A}" {
   m_sEntityPrefab "{24A824857ADC84CF}Prefabs/Weapons/MachineGuns/M240/MG_M240_Light.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710978D65360}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710978D65363}" {
   m_sEntityPrefab "{BA87F78D0E7E3A90}Prefabs/Weapons/MachineGuns/M240/MG_M240_Light_MDO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710978D60515}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}