SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Rifles (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D71097E6B53C6}" {
   m_sEntityPrefab "{3E413771E1834D2F}Prefabs/Weapons/Rifles/M16/Rifle_M16A2.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71097E6B53C8}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71097E6B53CE}" {
   m_sEntityPrefab "{5A987A8A13763769}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_M203.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71097E6B53CD}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71097E6B53CC}" {
   m_sEntityPrefab "{B036BA26CCFE9E5D}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71097E6B5433}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71097E6B1379}" {
   m_sEntityPrefab "{22529BCDC9439FCD}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_M203_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71097E6B137B}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71097E6C9A46}" {
   m_sEntityPrefab "{F7571A26F55AD8EF}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_OliveGreen_Solid.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71097E6C9A40}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71097E6CBA21}" {
   m_sEntityPrefab "{D3F274F6E2A5A924}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_M203_OliveGreen_Solid.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71097E6CBA20}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71097E6CBA23}" {
   m_sEntityPrefab "{0B0C4F7940C1CE26}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_4x20_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71097E6CBA28}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71097E6CBA2B}" {
   m_sEntityPrefab "{C29B073E2E583220}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_suppressor_M203_OliveGreen_Sand_Stripes.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71097E6CBA2A}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71097E6CBA35}" {
   m_sEntityPrefab "{29DD901C0664FC61}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_suppressor_4x20_OliveGreen_Sand_Stripes.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71097E6CBA34}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
 }
}