SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Machine Guns (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697B6CB8E766424E}" {
   m_sEntityPrefab "{D2B48DEBEF38D7D7}Prefabs/Weapons/MachineGuns/M249/MG_M249.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8E7664248}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8E7664235}" {
   m_sEntityPrefab "{D688A947EBC71A04}Prefabs/Weapons/MachineGuns/M249/MG_M249_PIP.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8E7664234}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8E7664232}" {
   m_sEntityPrefab "{D182DCDD72BF7E34}Prefabs/Weapons/MachineGuns/M60/MG_M60.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8E766C052}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8E766C050}" {
   m_sEntityPrefab "{49746016A5758D0C}Prefabs/Weapons/MachineGuns/M60/MG_M60E4_EXPS3.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8E7671F8A}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8E7671F85}" {
   m_sEntityPrefab "{E9059598E8595760}Prefabs/Weapons/MachineGuns/M60/MG_M60E4_TA648MDO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8E7671F84}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8E7671F87}" {
   m_sEntityPrefab "{A87B0A22462E20B1}Prefabs/Weapons/MachineGuns/M240/MG_M240.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8E7670F8C}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8E7670F8D}" {
   m_sEntityPrefab "{441C6358A2167AE3}Prefabs/Weapons/MachineGuns/M240/MG_M240_MDO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8E7670F8A}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8E7679C1E}" {
   m_sEntityPrefab "{24A824857ADC84CF}Prefabs/Weapons/MachineGuns/M240/MG_M240_Light.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8E7679C06}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8E767E068}" {
   m_sEntityPrefab "{BA87F78D0E7E3A90}Prefabs/Weapons/MachineGuns/M240/MG_M240_Light_MDO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8E767E069}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}