SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Carbine Rifles (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710949418AD6}" {
   m_sEntityPrefab "{D6516486D998AA0B}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine_weaver.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710949418AD0}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710949418ADE}" {
   m_sEntityPrefab "{6AB4AD4ADACB008B}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_EOT.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710949418ADF}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710949418ADC}" {
   m_sEntityPrefab "{139B1F6E64109536}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_EOT_pmag.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710949418ADD}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710949418ADA}" {
   m_sEntityPrefab "{4910F1F60DEE5DC9}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_rmr.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710949407110}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710949407112}" {
   m_sEntityPrefab "{19A852B58F40E4EB}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_rmr_warden.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710949407113}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710949407CA6}" {
   m_sEntityPrefab "{C20882A2C3211738}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_T1_sf.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710949407CB9}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710949407CB8}" {
   m_sEntityPrefab "{B5CF61A72D0BA15D}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_T1_warden.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710949407CBB}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71094940C28A}" {
   m_sEntityPrefab "{CBE985125ACE93DA}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_T1_pmag.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71094940C28B}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71094940C28C}" {
   m_sEntityPrefab "{C0F632AEF921F4C8}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_weaver_T1_pmag_warden.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71094940C28D}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}