SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Pistols (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697B6CB807C770D9}" {
   m_sEntityPrefab "{727ECDA84B3B2F33}Prefabs/Weapons/Handguns/P226/Handgun_P226.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB807C770DC}" {
     m_eItemType PISTOL
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB807C770D1}" {
   m_sEntityPrefab "{5C589CE4FFD6C047}Prefabs/Weapons/Handguns/P226/Handgun_P226_MOD1.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB807C770D0}" {
     m_eItemType PISTOL
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB807C770D7}" {
   m_sEntityPrefab "{069A8A4DDECB34BC}Prefabs/Weapons/Handguns/G19/Handgun_G19_NATO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB807C770D6}" {
     m_eItemType PISTOL
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB807C7A772}" {
   m_sEntityPrefab "{DD178C105E2655C5}Prefabs/Weapons/Handguns/G19/Handgun_G19_MOD1_NATO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB807C7A770}" {
     m_eItemType PISTOL
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}