SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Carbine Rifles (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697B6CB8DFC398B0}" {
   m_sEntityPrefab "{F97A4AC994231900}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8DFC398D7}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8DFC398D2}" {
   m_sEntityPrefab "{EF73725A81669E2C}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine_M203.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8DFBC7866}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8DFBC7868}" {
   m_sEntityPrefab "{D7690D6BB82B50D7}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8DFBC17E5}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8DFBC17E4}" {
   m_sEntityPrefab "{C417FBA57578B2E1}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_M203_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8DFBC17E7}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8DFBC0E13}" {
   m_sEntityPrefab "{92A0764C4EDF7C14}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_OliveGreen_Solid.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8DFBC0E12}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8DFBC0E15}" {
   m_sEntityPrefab "{135044000CA7BF85}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_M203_OliveGreen_Solid.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8DFBC0E14}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8DFBC0E17}" {
   m_sEntityPrefab "{EDE7F2CE157306AD}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_AP2k_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8DFBC0E3C}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8DFBC0E3F}" {
   m_sEntityPrefab "{83CE659F2C763F28}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_suppressor_OliveGreen_Sand_Stripes.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8DFBC0E3E}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB8DFBC0491}" {
   m_sEntityPrefab "{877128FBE22FF2C9}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_suppressor_AP2K_OliveGreen_Sand_Stripes.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB8DFBC049F}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
 }
}