SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Carbine Rifles (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D710946505182}" {
   m_sEntityPrefab "{F97A4AC994231900}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710946505188}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71094650518B}" {
   m_sEntityPrefab "{EF73725A81669E2C}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine_M203.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109465051B4}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7109465051B5}" {
   m_sEntityPrefab "{D7690D6BB82B50D7}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710946505209}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71094650520B}" {
   m_sEntityPrefab "{C417FBA57578B2E1}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_M203_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71094657CDD2}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71094657CDD5}" {
   m_sEntityPrefab "{92A0764C4EDF7C14}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_OliveGreen_Solid.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71094657CDD4}" {
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710946576A67}" {
   m_sEntityPrefab "{135044000CA7BF85}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_M203_OliveGreen_Solid.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710946576A64}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710946576A65}" {
   m_sEntityPrefab "{EDE7F2CE157306AD}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_AP2k_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710946576A6D}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710946576A72}" {
   m_sEntityPrefab "{83CE659F2C763F28}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_suppressor_OliveGreen_Sand_Stripes.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710946576A73}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D710946573BC7}" {
   m_sEntityPrefab "{877128FBE22FF2C9}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_suppressor_AP2K_OliveGreen_Sand_Stripes.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D710946573BC4}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
 }
}