SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Snipers (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697B6CB833B8A69D}" {
   m_sEntityPrefab "{9A2AA760B16BCDBE}Prefabs/Weapons/Rifles/M40/Rifle_M40A5.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB833B8A694}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697B6CB833B8A68A}" {
   m_sEntityPrefab "{8909A91CFF369BB3}Prefabs/Weapons/Rifles/M40/Rifle_M40A5_Optic.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697B6CB833B8A68B}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
 }
}