SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Launchers (WCS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7109728FA158}" {
   m_sEntityPrefab "{3DF204EEE0534EF2}Prefabs/Weapons/Launchers/FIM92_Stinger/Launcher_FIM92_Stinger.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109728FA15E}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 100
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7109728FA120}" {
   m_sEntityPrefab "{246737687711A367}Prefabs/Weapons/Launchers/FGM148_Javelin/Launcher_FGM148_Javelin.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109728FA122}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 200
     m_eRequiredRank COLONEL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7109728FA125}" {
   m_sEntityPrefab "{9C5C20FB0E01E64F}Prefabs/Weapons/Launchers/M72/Launcher_M72A3.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109728FA124}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 50
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7109728FA127}" {
   m_sEntityPrefab "{DA376E83952F1DFD}Prefabs/Weapons/Launchers/M2CG/Launcher_M2CG.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109728FA126}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 40
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7109728F8FD0}" {
   m_sEntityPrefab "{DB53366D8C521124}Prefabs/Weapons/Launchers/MK153/Launcher_MK153mod2_NoMBS.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109728F8FDE}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 40
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7109728F8FDD}" {
   m_sEntityPrefab "{35022055DCDDE98B}Prefabs/Weapons/Launchers/MK153/Launcher_MK153mod2.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109728F8FDC}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 40
    }
   }
  }
 }
}