SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Machine Guns (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7109767738F3}" {
   m_sEntityPrefab "{A87B0A22462E20B1}Prefabs/Weapons/MachineGuns/M240/MG_M240.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109767738FB}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7109767738F9}" {
   m_sEntityPrefab "{24A824857ADC84CF}Prefabs/Weapons/MachineGuns/M240/MG_M240_Light.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109767738F8}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7109767738E6}" {
   m_sEntityPrefab "{441C6358A2167AE3}Prefabs/Weapons/MachineGuns/M240/MG_M240_MDO.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71097677E7FE}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D71097677E7FC}" {
   m_sEntityPrefab "{BA87F78D0E7E3A90}Prefabs/Weapons/MachineGuns/M240/MG_M240_Light_MDO.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D71097677E7FB}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}