SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Launchers (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7109701B2425}" {
   m_sEntityPrefab "{DB53366D8C521124}Prefabs/Weapons/Launchers/MK153/Launcher_MK153mod2_NoMBS.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109701B242F}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7109701B242C}" {
   m_sEntityPrefab "{35022055DCDDE98B}Prefabs/Weapons/Launchers/MK153/Launcher_MK153mod2.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109701AAB6A}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7109701AAB6C}" {
   m_sEntityPrefab "{0228B8EFBA99AC1D}Prefabs/Weapons/Misc/SpectrumDevice/Device_SpectrumDevice_base.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109701AAB6F}" {
     m_eItemType ROCKET_LAUNCHER
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}