SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Snipers (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{697D7109657AEDCC}" {
   m_sEntityPrefab "{B31929F65F0D0279}Prefabs/Weapons/Rifles/M14/Rifle_M21.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109657AEDB2}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{697D7109657AEDB4}" {
   m_sEntityPrefab "{81EB948E6414BD6F}Prefabs/Weapons/Rifles/M14/Rifle_M21_ARTII.et"
   m_bEnabled 0
   m_aEntityDataList {
    SCR_ArsenalItem "{697D7109657AEDB5}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 0
    }
   }
  }
 }
}